# Generated by Django 5.2.10 on 2026-01-28 12:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetExportQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("png", "PNG"),
                            ("jpg", "JPEG"),
                            ("svg", "SVG"),
                            ("webp", "WebP"),
                            ("pdf", "PDF"),
                            ("avif", "AVIF"),
                        ],
                        max_length=10,
                    ),
                ),
                ("scale", models.FloatField(default=1.0)),
                (
                    "quality",
                    models.IntegerField(
                        default=90,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="asset_exports/"),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "design_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_queue",
                        to="projects.designcomponent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_export_queue",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Export Queue",
                "verbose_name_plural": "Asset Export Queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeExportConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("react", "React"),
                            ("react_native", "React Native"),
                            ("vue", "Vue"),
                            ("angular", "Angular"),
                            ("svelte", "Svelte"),
                            ("html", "HTML/CSS"),
                            ("ios", "iOS (SwiftUI)"),
                            ("android", "Android (Jetpack Compose)"),
                            ("flutter", "Flutter"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "styling",
                    models.CharField(
                        choices=[
                            ("tailwind", "Tailwind CSS"),
                            ("css", "Plain CSS"),
                            ("scss", "SCSS"),
                            ("css_modules", "CSS Modules"),
                            ("styled_components", "Styled Components"),
                            ("emotion", "Emotion"),
                            ("inline", "Inline Styles"),
                        ],
                        default="tailwind",
                        max_length=30,
                    ),
                ),
                ("use_typescript", models.BooleanField(default=True)),
                ("strict_types", models.BooleanField(default=True)),
                ("generate_props", models.BooleanField(default=True)),
                ("generate_types", models.BooleanField(default=True)),
                ("export_default", models.BooleanField(default=True)),
                ("responsive_breakpoints", models.JSONField(default=dict)),
                ("color_format", models.CharField(default="hex", max_length=20)),
                ("asset_path", models.CharField(default="/assets", max_length=255)),
                ("image_optimization", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_export_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Export Config",
                "verbose_name_plural": "Code Export Configs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CodeExportHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("export_type", models.CharField(default="full", max_length=30)),
                ("selected_elements", models.JSONField(default=list)),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="code_exports/"),
                ),
                ("output_url", models.URLField(blank=True)),
                ("file_size", models.BigIntegerField(default=0)),
                ("components_exported", models.IntegerField(default=0)),
                ("files_generated", models.IntegerField(default=0)),
                ("lines_of_code", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exports",
                        to="presentation_mode.codeexportconfig",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_exports",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="code_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Export History",
                "verbose_name_plural": "Code Export Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DevModeProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("default_framework", models.CharField(default="react", max_length=50)),
                (
                    "default_language",
                    models.CharField(default="typescript", max_length=50),
                ),
                (
                    "default_styling",
                    models.CharField(default="tailwind", max_length=50),
                ),
                ("unit_system", models.CharField(default="px", max_length=20)),
                ("rem_base", models.IntegerField(default=16)),
                ("indent_size", models.IntegerField(default=2)),
                ("use_semicolons", models.BooleanField(default=True)),
                ("quote_style", models.CharField(default="single", max_length=10)),
                ("include_comments", models.BooleanField(default=True)),
                ("include_measurements", models.BooleanField(default=True)),
                ("group_styles", models.BooleanField(default=True)),
                ("component_naming", models.CharField(default="pascal", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dev_mode_config",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dev Mode Project",
                "verbose_name_plural": "Dev Mode Projects",
            },
        ),
        migrations.CreateModel(
            name="DevModeInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("css_properties", models.JSONField(default=dict)),
                ("tailwind_classes", models.TextField(blank=True)),
                ("dimensions", models.JSONField(default=dict)),
                ("spacing", models.JSONField(default=dict)),
                ("typography", models.JSONField(default=dict)),
                ("colors", models.JSONField(default=dict)),
                ("react_code", models.TextField(blank=True)),
                ("vue_code", models.TextField(blank=True)),
                ("html_code", models.TextField(blank=True)),
                ("swift_code", models.TextField(blank=True)),
                ("kotlin_code", models.TextField(blank=True)),
                ("flutter_code", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dev_inspections",
                        to="projects.designcomponent",
                    ),
                ),
                (
                    "dev_mode_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="presentation_mode.devmodeproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dev Mode Inspection",
                "verbose_name_plural": "Dev Mode Inspections",
            },
        ),
        migrations.CreateModel(
            name="MeasurementOverlay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_element_id", models.CharField(max_length=100)),
                ("target_element_id", models.CharField(blank=True, max_length=100)),
                ("measurement_type", models.CharField(max_length=30)),
                ("value", models.FloatField()),
                ("unit", models.CharField(default="px", max_length=10)),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("direction", models.CharField(blank=True, max_length=20)),
                ("visible", models.BooleanField(default=True)),
                ("color", models.CharField(default="#ff0000", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dev_mode_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_overlays",
                        to="presentation_mode.devmodeproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement Overlay",
                "verbose_name_plural": "Measurement Overlays",
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "default_transition",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("fade", "Fade"),
                            ("slide", "Slide"),
                            ("push", "Push"),
                            ("zoom", "Zoom"),
                            ("flip", "Flip"),
                            ("dissolve", "Dissolve"),
                        ],
                        default="fade",
                        max_length=20,
                    ),
                ),
                ("transition_duration", models.IntegerField(default=500)),
                ("auto_advance", models.BooleanField(default=False)),
                ("auto_advance_delay", models.IntegerField(default=5000)),
                ("show_navigation", models.BooleanField(default=True)),
                ("show_slide_numbers", models.BooleanField(default=True)),
                ("show_progress_bar", models.BooleanField(default=True)),
                ("loop", models.BooleanField(default=False)),
                (
                    "background_color",
                    models.CharField(default="#000000", max_length=50),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="presentations/"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="presentation_logos/"
                    ),
                ),
                ("logo_position", models.CharField(default="top-left", max_length=20)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "share_link",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("password_protected", models.BooleanField(default=False)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                ("allow_comments", models.BooleanField(default=True)),
                ("allow_download", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("last_viewed", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentation",
                "verbose_name_plural": "Presentations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PresentationSlide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.JSONField(default=dict)),
                (
                    "snapshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="slide_snapshots/"
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("full", "Full Bleed"),
                            ("centered", "Centered"),
                            ("split", "Split"),
                            ("grid", "Grid"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "transition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("fade", "Fade"),
                            ("slide", "Slide"),
                            ("push", "Push"),
                            ("zoom", "Zoom"),
                            ("flip", "Flip"),
                            ("dissolve", "Dissolve"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("transition_duration", models.IntegerField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("speaker_notes", models.TextField(blank=True)),
                ("background_color", models.CharField(blank=True, max_length=50)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="slide_backgrounds/"
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presentation_slides",
                        to="projects.designcomponent",
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="presentation_mode.presentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentation Slide",
                "verbose_name_plural": "Presentation Slides",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PresentationViewer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("first_viewed", models.DateTimeField(auto_now_add=True)),
                ("last_viewed", models.DateTimeField(auto_now=True)),
                ("view_count", models.IntegerField(default=1)),
                ("slides_viewed", models.JSONField(default=list)),
                ("time_spent", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewers",
                        to="presentation_mode.presentation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viewed_presentations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentation Viewer",
                "verbose_name_plural": "Presentation Viewers",
            },
        ),
        migrations.CreateModel(
            name="SlideAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("hotspot", "Hotspot"),
                            ("note", "Note"),
                            ("callout", "Callout"),
                            ("link", "Link"),
                            ("video", "Video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("content", models.JSONField(default=dict)),
                ("visible_in_presentation", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="presentation_mode.presentationslide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slide Annotation",
                "verbose_name_plural": "Slide Annotations",
                "ordering": ["position_y", "position_x"],
            },
        ),
    ]
