# Generated by Django 5.2.11 on 2026-02-27 20:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("ja", "Japanese"),
                            ("zh", "Chinese"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("default_canvas_width", models.IntegerField(default=1920)),
                ("default_canvas_height", models.IntegerField(default=1080)),
                (
                    "default_background_color",
                    models.CharField(default="#FFFFFF", max_length=20),
                ),
                ("show_grid", models.BooleanField(default=True)),
                ("snap_to_grid", models.BooleanField(default=True)),
                ("grid_size", models.IntegerField(default=10)),
                ("show_rulers", models.BooleanField(default=True)),
                ("auto_save", models.BooleanField(default=True)),
                (
                    "auto_save_interval",
                    models.IntegerField(
                        default=30, help_text="Auto-save interval in seconds"
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                ("notify_on_comment", models.BooleanField(default=True)),
                ("notify_on_mention", models.BooleanField(default=True)),
                ("notify_on_share", models.BooleanField(default=True)),
                ("marketing_emails", models.BooleanField(default=False)),
                ("weekly_digest", models.BooleanField(default=True)),
                (
                    "preferred_ai_style",
                    models.CharField(default="modern", max_length=50),
                ),
                (
                    "preferred_design_type",
                    models.CharField(default="ui_ux", max_length=50),
                ),
                ("ai_suggestions_enabled", models.BooleanField(default=True)),
                ("high_contrast", models.BooleanField(default=False)),
                ("reduced_motion", models.BooleanField(default=False)),
                ("font_size_scale", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User preferences",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("register", "Registration"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                            ("email_verify", "Email Verification"),
                            ("profile_update", "Profile Update"),
                            ("project_create", "Project Created"),
                            ("project_update", "Project Updated"),
                            ("project_delete", "Project Deleted"),
                            ("project_share", "Project Shared"),
                            ("export", "Export"),
                            ("ai_request", "AI Request"),
                            ("team_create", "Team Created"),
                            ("team_member_add", "Team Member Added"),
                            ("team_member_remove", "Team Member Removed"),
                            ("role_change", "Role Changed"),
                            ("subscription_change", "Subscription Changed"),
                            ("api_key_create", "API Key Created"),
                            ("api_key_revoke", "API Key Revoked"),
                            ("settings_change", "Settings Changed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="accounts_au_user_id_1110c4_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="accounts_au_action_918219_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="accounts_au_resourc_30880d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_em_token_5f2b37_idx"),
                    models.Index(
                        fields=["user", "is_used"],
                        name="accounts_em_user_id_33bc9c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_attempted", models.CharField(max_length=150)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                (
                    "provider",
                    models.CharField(blank=True, default="email", max_length=20),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="accounts_lo_user_id_6a9788_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="accounts_lo_ip_addr_eed231_idx",
                    ),
                    models.Index(
                        fields=["success"], name="accounts_lo_success_3a0026_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_pa_token_affdf2_idx"),
                    models.Index(
                        fields=["user", "is_used"],
                        name="accounts_pa_user_id_023f8d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/%Y/%m/"
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, default="")),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("company", models.CharField(blank=True, max_length=150)),
                ("website", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_onboarded", models.BooleanField(default=False)),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                ("total_designs_created", models.PositiveIntegerField(default=0)),
                ("total_ai_requests", models.PositiveIntegerField(default=0)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="accounts_us_user_id_806298_idx"
                    ),
                    models.Index(
                        fields=["is_email_verified"],
                        name="accounts_us_is_emai_5392d7_idx",
                    ),
                ],
            },
        ),
    ]
