# Generated by Django 5.2.7 on 2025-12-04 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("provider", models.CharField(blank=True, max_length=20, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("risk_score", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["email", "timestamp"],
                        name="authenticat_email_52dbf5_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="authenticat_ip_addr_95756c_idx",
                    ),
                    models.Index(
                        fields=["success", "timestamp"],
                        name="authenticat_success_9d1f06_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("github", "GitHub"),
                            ("firebase", "Firebase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("redirect_uri", models.URLField()),
                (
                    "code_verifier",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("nonce", models.CharField(blank=True, max_length=128, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state"], name="authenticat_state_c620b1_idx"),
                    models.Index(
                        fields=["expires_at"], name="authenticat_expires_8efa0f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSecurityProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("two_factor_enabled", models.BooleanField(default=False)),
                (
                    "two_factor_secret_encrypted",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "two_factor_backup_codes_encrypted",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "two_factor_method",
                    models.CharField(
                        choices=[
                            ("totp", "Authenticator App"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        default="totp",
                        max_length=20,
                    ),
                ),
                ("require_password_change", models.BooleanField(default=False)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_user_agent", models.TextField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "locked_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("failed_login_count", models.IntegerField(default=0)),
                ("lockout_until", models.DateTimeField(blank=True, null=True)),
                ("trusted_devices", models.JSONField(blank=True, default=list)),
                ("active_sessions_count", models.IntegerField(default=0)),
                ("max_sessions_allowed", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Security Profile",
                "verbose_name_plural": "User Security Profiles",
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key_prefix", models.CharField(max_length=8)),
                ("key_hash", models.CharField(max_length=128)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("rate_limit", models.IntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["key_prefix"], name="authenticat_key_pre_d5c064_idx"
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="authenticat_user_id_297b16_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("github", "GitHub"),
                            ("firebase", "Firebase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                (
                    "provider_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "provider_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("access_token_encrypted", models.TextField(blank=True, null=True)),
                ("refresh_token_encrypted", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("profile_data", models.JSONField(blank=True, default=dict)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "provider"],
                        name="authenticat_user_id_71c276_idx",
                    ),
                    models.Index(
                        fields=["provider", "provider_user_id"],
                        name="authenticat_provide_16bdaa_idx",
                    ),
                ],
                "unique_together": {("provider", "provider_user_id")},
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                (
                    "event_category",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("authorization", "Authorization"),
                            ("data_access", "Data Access"),
                            ("data_modification", "Data Modification"),
                            ("security_change", "Security Change"),
                            ("system", "System"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "event_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("warning", "Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("request_path", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="authenticat_event_t_3c10c1_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="authenticat_user_id_994e96_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="authenticat_ip_addr_ff73eb_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "timestamp"],
                        name="authenticat_risk_le_633481_idx",
                    ),
                ],
            },
        ),
    ]
