# Generated by Django 5.2.7 on 2025-10-27 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FontFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('font_family', models.CharField(max_length=255)),
                ('regular_url', models.URLField(blank=True)),
                ('bold_url', models.URLField(blank=True)),
                ('italic_url', models.URLField(blank=True)),
                ('bold_italic_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans Serif'), ('monospace', 'Monospace'), ('display', 'Display'), ('handwriting', 'Handwriting')], max_length=50)),
                ('is_google_font', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('icon', 'Icon'), ('font', 'Font'), ('video', 'Video'), ('audio', 'Audio'), ('svg', 'SVG')], max_length=20)),
                ('file_url', models.URLField()),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colors', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', '-created_at'],
            },
        ),
    ]
