# Generated by Django 5.2.10 on 2026-01-28 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        ("teams", "0003_alter_comment_mentions_alter_comment_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StickyNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("yellow", "Yellow"),
                            ("pink", "Pink"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("orange", "Orange"),
                            ("purple", "Purple"),
                        ],
                        default="yellow",
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(default=200)),
                ("height", models.FloatField(default=200)),
                ("rotation", models.FloatField(default=0)),
                ("z_index", models.IntegerField(default=0)),
                ("font_size", models.IntegerField(default=16)),
                ("text_align", models.CharField(default="left", max_length=20)),
                ("locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sticky_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sticky Note",
                "verbose_name_plural": "Sticky Notes",
                "ordering": ["z_index"],
            },
        ),
        migrations.CreateModel(
            name="StickyNoteVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sticky_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records",
                        to="whiteboard.stickynote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sticky_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sticky Note Vote",
                "verbose_name_plural": "Sticky Note Votes",
                "unique_together": {("sticky_note", "user")},
            },
        ),
        migrations.AddField(
            model_name="stickynote",
            name="votes",
            field=models.ManyToManyField(
                related_name="voted_notes",
                through="whiteboard.StickyNoteVote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Whiteboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "board_type",
                    models.CharField(
                        choices=[
                            ("brainstorm", "Brainstorm"),
                            ("flowchart", "Flowchart"),
                            ("wireframe", "Wireframe"),
                            ("mindmap", "Mind Map"),
                            ("planning", "Planning"),
                            ("retrospective", "Retrospective"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(default="#f8f9fa", max_length=50),
                ),
                ("background_pattern", models.CharField(default="dots", max_length=30)),
                ("grid_size", models.IntegerField(default=20)),
                ("snap_to_grid", models.BooleanField(default=True)),
                ("bounds_min_x", models.FloatField(default=-10000)),
                ("bounds_min_y", models.FloatField(default=-10000)),
                ("bounds_max_x", models.FloatField(default=10000)),
                ("bounds_max_y", models.FloatField(default=10000)),
                ("default_zoom", models.FloatField(default=1.0)),
                ("default_center_x", models.FloatField(default=0)),
                ("default_center_y", models.FloatField(default=0)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="whiteboards/"),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "share_link",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("allow_guest_editing", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_template", models.BooleanField(default=False)),
                ("tags", models.JSONField(default=list)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboards",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboards",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_whiteboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard",
                "verbose_name_plural": "Whiteboards",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Timer", max_length=100)),
                ("duration", models.IntegerField(default=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stopped", "Stopped"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                        ],
                        default="stopped",
                        max_length=20,
                    ),
                ),
                ("elapsed", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("play_sound", models.BooleanField(default=True)),
                ("visible_to_all", models.BooleanField(default=True)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whiteboard_timers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timers",
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timer",
                "verbose_name_plural": "Timers",
            },
        ),
        migrations.AddField(
            model_name="stickynote",
            name="whiteboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sticky_notes",
                to="whiteboard.whiteboard",
            ),
        ),
        migrations.CreateModel(
            name="WhiteboardCollaborator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("editor", "Editor"),
                            ("admin", "Admin"),
                        ],
                        default="editor",
                        max_length=20,
                    ),
                ),
                ("cursor_color", models.CharField(default="#6366f1", max_length=50)),
                ("last_x", models.FloatField(blank=True, null=True)),
                ("last_y", models.FloatField(blank=True, null=True)),
                ("last_zoom", models.FloatField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whiteboard_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborator_roles",
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Collaborator",
                "verbose_name_plural": "Whiteboard Collaborators",
                "unique_together": {("whiteboard", "user")},
            },
        ),
        migrations.AddField(
            model_name="whiteboard",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborated_whiteboards",
                through="whiteboard.WhiteboardCollaborator",
                through_fields=("whiteboard", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="WhiteboardEmoji",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("emoji", models.CharField(max_length=10)),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("size", models.IntegerField(default=32)),
                ("is_temporary", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard_emojis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emojis",
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Emoji",
                "verbose_name_plural": "Whiteboard Emojis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhiteboardGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("locked", models.BooleanField(default=False)),
                ("z_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whiteboard_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_groups",
                        to="whiteboard.whiteboardgroup",
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Group",
                "verbose_name_plural": "Whiteboard Groups",
                "ordering": ["z_index"],
            },
        ),
        migrations.AddField(
            model_name="stickynote",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sticky_notes",
                to="whiteboard.whiteboardgroup",
            ),
        ),
        migrations.CreateModel(
            name="WhiteboardImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="whiteboard_images/")),
                ("image_url", models.URLField(blank=True)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("rotation", models.FloatField(default=0)),
                ("original_width", models.IntegerField(blank=True, null=True)),
                ("original_height", models.IntegerField(blank=True, null=True)),
                ("opacity", models.FloatField(default=1.0)),
                ("corner_radius", models.FloatField(default=0)),
                ("border_color", models.CharField(blank=True, max_length=50)),
                ("border_width", models.FloatField(default=0)),
                ("z_index", models.IntegerField(default=0)),
                ("locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="whiteboard.whiteboardgroup",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whiteboard_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Image",
                "verbose_name_plural": "Whiteboard Images",
                "ordering": ["z_index"],
            },
        ),
        migrations.CreateModel(
            name="WhiteboardSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(default=500)),
                ("height", models.FloatField(default=400)),
                (
                    "background_color",
                    models.CharField(default="#f3f4f6", max_length=50),
                ),
                ("border_color", models.CharField(default="#d1d5db", max_length=50)),
                (
                    "title_background",
                    models.CharField(default="#6366f1", max_length=50),
                ),
                ("title_color", models.CharField(default="#ffffff", max_length=50)),
                ("order", models.IntegerField(default=0)),
                ("locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whiteboard_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Section",
                "verbose_name_plural": "Whiteboard Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhiteboardShape",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shape_type",
                    models.CharField(
                        choices=[
                            ("rectangle", "Rectangle"),
                            ("ellipse", "Ellipse"),
                            ("triangle", "Triangle"),
                            ("diamond", "Diamond"),
                            ("star", "Star"),
                            ("arrow", "Arrow"),
                            ("line", "Line"),
                            ("polygon", "Polygon"),
                            ("cloud", "Cloud"),
                            ("cylinder", "Cylinder"),
                            ("parallelogram", "Parallelogram"),
                            ("hexagon", "Hexagon"),
                            ("trapezoid", "Trapezoid"),
                            ("callout", "Callout"),
                            ("freeform", "Freeform"),
                        ],
                        max_length=30,
                    ),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(default=100)),
                ("height", models.FloatField(default=100)),
                ("rotation", models.FloatField(default=0)),
                ("start_x", models.FloatField(blank=True, null=True)),
                ("start_y", models.FloatField(blank=True, null=True)),
                ("end_x", models.FloatField(blank=True, null=True)),
                ("end_y", models.FloatField(blank=True, null=True)),
                ("points", models.JSONField(blank=True, null=True)),
                ("fill_color", models.CharField(default="#ffffff", max_length=50)),
                ("fill_opacity", models.FloatField(default=1.0)),
                ("stroke_color", models.CharField(default="#000000", max_length=50)),
                ("stroke_width", models.FloatField(default=2)),
                ("stroke_style", models.CharField(default="solid", max_length=20)),
                ("corner_radius", models.FloatField(default=0)),
                ("text_content", models.TextField(blank=True)),
                ("text_color", models.CharField(default="#000000", max_length=50)),
                ("font_size", models.IntegerField(default=14)),
                ("text_align", models.CharField(default="center", max_length=20)),
                ("start_arrow", models.CharField(default="none", max_length=20)),
                ("end_arrow", models.CharField(default="none", max_length=20)),
                ("z_index", models.IntegerField(default=0)),
                ("locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whiteboard_shapes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shapes",
                        to="whiteboard.whiteboardgroup",
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shapes",
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Shape",
                "verbose_name_plural": "Whiteboard Shapes",
                "ordering": ["z_index"],
            },
        ),
        migrations.CreateModel(
            name="WhiteboardComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="whiteboard.whiteboardcomment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_whiteboard_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sticky_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="whiteboard.stickynote",
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="whiteboard.whiteboard",
                    ),
                ),
                (
                    "shape",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="whiteboard.whiteboardshape",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Comment",
                "verbose_name_plural": "Whiteboard Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_anchor",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("right", "Right"),
                            ("bottom", "Bottom"),
                            ("left", "Left"),
                            ("center", "Center"),
                            ("auto", "Auto"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "target_anchor",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("right", "Right"),
                            ("bottom", "Bottom"),
                            ("left", "Left"),
                            ("center", "Center"),
                            ("auto", "Auto"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("line", "Straight Line"),
                            ("elbow", "Elbow"),
                            ("curve", "Curve"),
                        ],
                        default="elbow",
                        max_length=20,
                    ),
                ),
                ("stroke_color", models.CharField(default="#000000", max_length=50)),
                ("stroke_width", models.FloatField(default=2)),
                ("stroke_style", models.CharField(default="solid", max_length=20)),
                ("start_arrow", models.CharField(default="none", max_length=20)),
                ("end_arrow", models.CharField(default="arrow", max_length=20)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("label_position", models.FloatField(default=0.5)),
                ("control_points", models.JSONField(blank=True, null=True)),
                ("z_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_sticky",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connectors",
                        to="whiteboard.stickynote",
                    ),
                ),
                (
                    "target_sticky",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connectors",
                        to="whiteboard.stickynote",
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="whiteboard.whiteboard",
                    ),
                ),
                (
                    "source_shape",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connectors",
                        to="whiteboard.whiteboardshape",
                    ),
                ),
                (
                    "target_shape",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connectors",
                        to="whiteboard.whiteboardshape",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connector",
                "verbose_name_plural": "Connectors",
                "ordering": ["z_index"],
            },
        ),
        migrations.CreateModel(
            name="WhiteboardTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("template_data", models.JSONField(default=dict)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="whiteboard_templates/"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whiteboard_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Template",
                "verbose_name_plural": "Whiteboard Templates",
                "ordering": ["-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="WhiteboardText",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("rotation", models.FloatField(default=0)),
                ("font_family", models.CharField(default="Inter", max_length=100)),
                ("font_size", models.IntegerField(default=24)),
                ("font_weight", models.CharField(default="normal", max_length=20)),
                ("font_style", models.CharField(default="normal", max_length=20)),
                ("text_color", models.CharField(default="#000000", max_length=50)),
                ("text_align", models.CharField(default="left", max_length=20)),
                ("underline", models.BooleanField(default=False)),
                ("strikethrough", models.BooleanField(default=False)),
                ("max_width", models.FloatField(blank=True, null=True)),
                ("z_index", models.IntegerField(default=0)),
                ("locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whiteboard_texts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_elements",
                        to="whiteboard.whiteboardgroup",
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_elements",
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteboard Text",
                "verbose_name_plural": "Whiteboard Texts",
                "ordering": ["z_index"],
            },
        ),
    ]
