# Generated by Django 5.2.10 on 2026-01-28 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        ("teams", "0004_alter_task_assigned_to_alter_task_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("slack", "Slack"), ("teams", "Microsoft Teams")],
                        max_length=20,
                    ),
                ),
                ("command", models.CharField(max_length=100)),
                ("arguments", models.TextField(blank=True)),
                ("workspace_id", models.CharField(max_length=100)),
                ("channel_id", models.CharField(max_length=100)),
                ("user_external_id", models.CharField(max_length=100)),
                ("response_sent", models.BooleanField(default=False)),
                ("response_content", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("slack", "Slack"), ("teams", "Microsoft Teams")],
                        max_length=20,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("design_share", "Design Shared"),
                            ("comment", "Comment"),
                            ("mention", "Mention"),
                            ("update", "Design Updated"),
                            ("export", "Export Completed"),
                            ("bot_command", "Bot Command"),
                            ("notification", "Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("workspace_id", models.CharField(max_length=100)),
                ("channel_id", models.CharField(max_length=100)),
                ("message_content", models.JSONField(default=dict)),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("external_message_id", models.CharField(blank=True, max_length=100)),
                ("thread_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MicrosoftTeamsWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(max_length=100)),
                ("ms_team_id", models.CharField(max_length=100, unique=True)),
                ("team_name", models.CharField(max_length=255)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("webhook_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_post_designs", models.BooleanField(default=False)),
                (
                    "notification_channel_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("token_expires_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_workspaces",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Microsoft Teams Workspaces",
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_enabled", models.BooleanField(default=True)),
                ("slack_dm_enabled", models.BooleanField(default=True)),
                ("slack_mention_enabled", models.BooleanField(default=True)),
                ("teams_enabled", models.BooleanField(default=True)),
                ("teams_dm_enabled", models.BooleanField(default=True)),
                ("teams_mention_enabled", models.BooleanField(default=True)),
                ("notify_on_comments", models.BooleanField(default=True)),
                ("notify_on_mentions", models.BooleanField(default=True)),
                ("notify_on_project_updates", models.BooleanField(default=True)),
                ("notify_on_team_activity", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "quiet_hours_timezone",
                    models.CharField(default="UTC", max_length=50),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlackWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workspace_id", models.CharField(max_length=50, unique=True)),
                ("workspace_name", models.CharField(max_length=255)),
                ("access_token", models.TextField()),
                ("bot_token", models.TextField(blank=True)),
                ("bot_user_id", models.CharField(blank=True, max_length=50)),
                ("webhook_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_post_designs", models.BooleanField(default=False)),
                ("notification_channel", models.CharField(blank=True, max_length=100)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_workspaces",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="SlackChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=50)),
                ("channel_name", models.CharField(max_length=255)),
                ("channel_type", models.CharField(default="channel", max_length=20)),
                ("notify_on_comment", models.BooleanField(default=True)),
                ("notify_on_update", models.BooleanField(default=True)),
                ("notify_on_export", models.BooleanField(default=False)),
                ("notify_on_share", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_channels",
                        to="projects.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="slack_teams_integration.slackworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["channel_name"],
                "unique_together": {("workspace", "channel_id")},
            },
        ),
        migrations.CreateModel(
            name="TeamsChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=100)),
                ("channel_name", models.CharField(max_length=255)),
                ("channel_type", models.CharField(default="standard", max_length=20)),
                ("notify_on_comment", models.BooleanField(default=True)),
                ("notify_on_update", models.BooleanField(default=True)),
                ("notify_on_export", models.BooleanField(default=False)),
                ("notify_on_share", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_channels",
                        to="projects.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="slack_teams_integration.microsoftteamsworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["channel_name"],
                "unique_together": {("workspace", "channel_id")},
            },
        ),
    ]
