# Generated by Django 5.2.7 on 2025-10-27 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('sidebar', 'Sidebar'), ('card', 'Card'), ('button', 'Button'), ('form', 'Form'), ('navigation', 'Navigation'), ('hero', 'Hero Section')], max_length=30)),
                ('design_data', models.JSONField(default=dict)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('social_media', 'Social Media'), ('presentation', 'Presentation'), ('poster', 'Poster'), ('flyer', 'Flyer'), ('ui_kit', 'UI Kit'), ('mobile_app', 'Mobile App'), ('web_design', 'Web Design'), ('logo', 'Logo'), ('business_card', 'Business Card'), ('infographic', 'Infographic')], max_length=30)),
                ('design_data', models.JSONField(default=dict)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('tags', models.JSONField(default=list)),
                ('color_palette', models.JSONField(default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('use_count', models.IntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', '-created_at'],
            },
        ),
    ]
