# Generated by Django 5.2.10 on 2026-01-28 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design_systems", "__first__"),
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        ("teams", "0003_alter_comment_mentions_alter_comment_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="component_sets/"
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(default=list)),
                ("is_published", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("instance_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_sets",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_sets",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_sets",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Set",
                "verbose_name_plural": "Component Sets",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ComponentProperty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("variant", "Variant"),
                            ("boolean", "Boolean"),
                            ("text", "Text"),
                            ("instance_swap", "Instance Swap"),
                            ("number", "Number"),
                        ],
                        max_length=20,
                    ),
                ),
                ("default_value", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_hidden", models.BooleanField(default=False)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("step", models.FloatField(blank=True, null=True)),
                ("placeholder", models.CharField(blank=True, max_length=255)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="component_variants.componentset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Property",
                "verbose_name_plural": "Component Properties",
                "ordering": ["order", "name"],
                "unique_together": {("component_set", "name")},
            },
        ),
        migrations.CreateModel(
            name="ComponentVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("property_values", models.JSONField(default=dict)),
                ("design_data", models.JSONField(default=dict)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(default=100)),
                ("height", models.FloatField(default=100)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="variant_thumbnails/"
                    ),
                ),
                ("is_base", models.BooleanField(default=False)),
                ("variant_key", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="component_variants.componentset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Variant",
                "verbose_name_plural": "Component Variants",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="componentset",
            name="default_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="component_variants.componentvariant",
            ),
        ),
        migrations.CreateModel(
            name="ComponentInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_overrides", models.JSONField(default=dict)),
                ("style_overrides", models.JSONField(default=dict)),
                ("content_overrides", models.JSONField(default=dict)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("rotation", models.FloatField(default=0)),
                ("scale_x", models.FloatField(default=1.0)),
                ("scale_y", models.FloatField(default=1.0)),
                ("visible", models.BooleanField(default=True)),
                ("locked", models.BooleanField(default=False)),
                ("is_detached", models.BooleanField(default=False)),
                ("is_synced", models.BooleanField(default=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_component",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_instance_config",
                        to="projects.designcomponent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_instances",
                        to="projects.project",
                    ),
                ),
                (
                    "component_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="component_variants.componentset",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="component_variants.componentvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Instance",
                "verbose_name_plural": "Component Instances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("order", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="component_variants.componentproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Option",
                "verbose_name_plural": "Property Options",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VariantOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_path", models.CharField(max_length=500)),
                (
                    "override_type",
                    models.CharField(
                        choices=[
                            ("style", "Style Override"),
                            ("layout", "Layout Override"),
                            ("content", "Content Override"),
                            ("visibility", "Visibility Override"),
                        ],
                        max_length=20,
                    ),
                ),
                ("property_name", models.CharField(max_length=100)),
                ("original_value", models.JSONField(blank=True, null=True)),
                ("override_value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="component_variants.componentvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant Override",
                "verbose_name_plural": "Variant Overrides",
            },
        ),
        migrations.CreateModel(
            name="ComponentSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("allowed_types", models.JSONField(default=list)),
                ("default_content", models.JSONField(blank=True, null=True)),
                ("min_items", models.IntegerField(default=0)),
                ("max_items", models.IntegerField(blank=True, null=True)),
                ("required", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="component_variants.componentset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Slot",
                "verbose_name_plural": "Component Slots",
                "ordering": ["order"],
                "unique_together": {("component_set", "name")},
            },
        ),
        migrations.CreateModel(
            name="InteractiveState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("hover", "Hover"),
                            ("pressed", "Pressed"),
                            ("focus", "Focus"),
                            ("focus_visible", "Focus Visible"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("loading", "Loading"),
                            ("error", "Error"),
                            ("success", "Success"),
                            ("selected", "Selected"),
                            ("checked", "Checked"),
                            ("indeterminate", "Indeterminate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("trigger", models.CharField(default="hover", max_length=50)),
                ("style_changes", models.JSONField(default=dict)),
                ("transition_duration", models.IntegerField(default=150)),
                (
                    "transition_easing",
                    models.CharField(default="ease-out", max_length=50),
                ),
                ("transition_properties", models.JSONField(default=list)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactive_states",
                        to="component_variants.componentvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interactive State",
                "verbose_name_plural": "Interactive States",
                "ordering": ["order"],
                "unique_together": {("variant", "state_type")},
            },
        ),
    ]
