# Generated by Django 6.0.2 on 2026-02-28 18:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_webhook_user"),
        ("teams", "0004_alter_task_assigned_to_alter_task_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "graph_data",
                    models.JSONField(
                        default=dict, help_text="Visual graph: nodes, edges, positions"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("retry_delay_seconds", models.IntegerField(default=60)),
                ("timeout_seconds", models.IntegerField(default=300)),
                ("run_as_async", models.BooleanField(default=True)),
                ("total_runs", models.IntegerField(default=0)),
                ("successful_runs", models.IntegerField(default=0)),
                ("failed_runs", models.IntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("export_png", "Export as PNG"),
                            ("export_pdf", "Export as PDF"),
                            ("export_svg", "Export as SVG"),
                            ("export_all_formats", "Export All Formats"),
                            ("magic_resize", "Magic Resize"),
                            ("publish_web", "Publish to Web"),
                            ("schedule_social", "Schedule Social Post"),
                            ("send_email", "Send Email"),
                            ("send_slack", "Send Slack Message"),
                            ("send_webhook", "Send Webhook"),
                            ("notify_team", "Notify Team"),
                            ("update_brand_colors", "Update Brand Colors"),
                            ("apply_template", "Apply Template"),
                            ("run_accessibility_check", "Run Accessibility Check"),
                            ("run_qa_check", "Run QA Check"),
                            ("condition", "Conditional Branch"),
                            ("delay", "Wait/Delay"),
                            ("loop", "Loop/Repeat"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Action-specific parameters"
                    ),
                ),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                ("condition_expression", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "next_action_on_failure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prev_failure",
                        to="notifications.workflowaction",
                    ),
                ),
                (
                    "next_action_on_success",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prev_success",
                        to="notifications.workflowaction",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="notifications.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timed_out", "Timed Out"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trigger_type", models.CharField(blank=True, max_length=30)),
                ("trigger_data", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("output", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="notifications.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="notifications.workflowaction",
                    ),
                ),
                (
                    "workflow_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="notifications.workflowrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("design_approved", "Design Approved"),
                            ("design_updated", "Design Updated"),
                            ("comment_added", "Comment Added"),
                            ("brand_colors_changed", "Brand Colors Changed"),
                            ("schedule", "Scheduled"),
                            ("webhook", "Webhook"),
                            ("manual", "Manual"),
                            ("project_created", "Project Created"),
                            ("export_completed", "Export Completed"),
                            ("team_member_joined", "Team Member Joined"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Trigger-specific configuration"
                    ),
                ),
                ("cron_expression", models.CharField(blank=True, max_length=100)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="notifications.workflow",
                    ),
                ),
            ],
        ),
    ]
