# Generated by Django 5.2.10 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Path", max_length=255)),
                (
                    "path_type",
                    models.CharField(
                        choices=[
                            ("open", "Open Path"),
                            ("closed", "Closed Path"),
                            ("compound", "Compound Path"),
                        ],
                        default="closed",
                        max_length=20,
                    ),
                ),
                ("path_data", models.TextField(help_text="SVG path data string")),
                (
                    "path_points",
                    models.JSONField(
                        default=list, help_text="Detailed path points with handles"
                    ),
                ),
                (
                    "fill_color",
                    models.CharField(blank=True, default="#000000", max_length=50),
                ),
                ("fill_opacity", models.FloatField(default=1.0)),
                (
                    "fill_rule",
                    models.CharField(
                        choices=[("nonzero", "Non-Zero"), ("evenodd", "Even-Odd")],
                        default="nonzero",
                        max_length=20,
                    ),
                ),
                (
                    "fill_gradient",
                    models.JSONField(
                        blank=True, help_text="Gradient definition", null=True
                    ),
                ),
                (
                    "stroke_color",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("stroke_width", models.FloatField(default=1.0)),
                ("stroke_opacity", models.FloatField(default=1.0)),
                (
                    "stroke_cap",
                    models.CharField(
                        choices=[
                            ("butt", "Butt"),
                            ("round", "Round"),
                            ("square", "Square"),
                        ],
                        default="round",
                        max_length=20,
                    ),
                ),
                (
                    "stroke_join",
                    models.CharField(
                        choices=[
                            ("miter", "Miter"),
                            ("round", "Round"),
                            ("bevel", "Bevel"),
                        ],
                        default="round",
                        max_length=20,
                    ),
                ),
                ("stroke_miter_limit", models.FloatField(default=4.0)),
                (
                    "stroke_dash_array",
                    models.JSONField(default=list, help_text="Dash pattern array"),
                ),
                ("stroke_dash_offset", models.FloatField(default=0.0)),
                (
                    "transform_matrix",
                    models.JSONField(
                        default=list, help_text="2D transformation matrix [a,b,c,d,e,f]"
                    ),
                ),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("width", models.FloatField(default=100)),
                ("height", models.FloatField(default=100)),
                ("z_index", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_paths",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_paths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vector Path",
                "verbose_name_plural": "Vector Paths",
                "ordering": ["z_index"],
            },
        ),
        migrations.CreateModel(
            name="PenToolSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("tool_settings", models.JSONField(default=dict)),
                ("temp_points", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pen_sessions",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pen_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vector_editing.vectorpath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pen Tool Session",
                "verbose_name_plural": "Pen Tool Sessions",
            },
        ),
        migrations.CreateModel(
            name="PathPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                (
                    "handle_in_x",
                    models.FloatField(default=0, help_text="Incoming handle X offset"),
                ),
                (
                    "handle_in_y",
                    models.FloatField(default=0, help_text="Incoming handle Y offset"),
                ),
                (
                    "handle_out_x",
                    models.FloatField(default=0, help_text="Outgoing handle X offset"),
                ),
                (
                    "handle_out_y",
                    models.FloatField(default=0, help_text="Outgoing handle Y offset"),
                ),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("corner", "Corner Point"),
                            ("smooth", "Smooth Point"),
                            ("symmetric", "Symmetric Point"),
                            ("disconnected", "Disconnected Handles"),
                        ],
                        default="corner",
                        max_length=20,
                    ),
                ),
                (
                    "corner_radius",
                    models.FloatField(default=0, help_text="Corner rounding radius"),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="vector_editing.vectorpath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Path Point",
                "verbose_name_plural": "Path Points",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PathOffset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "offset_type",
                    models.CharField(
                        choices=[
                            ("expand", "Expand"),
                            ("contract", "Contract"),
                            ("outline_stroke", "Outline Stroke"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "offset_value",
                    models.FloatField(help_text="Offset distance in pixels"),
                ),
                (
                    "join_type",
                    models.CharField(
                        choices=[
                            ("miter", "Miter"),
                            ("round", "Round"),
                            ("bevel", "Bevel"),
                        ],
                        default="miter",
                        max_length=20,
                    ),
                ),
                ("miter_limit", models.FloatField(default=4.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result_path",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offset_result",
                        to="vector_editing.vectorpath",
                    ),
                ),
                (
                    "source_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offset_operations",
                        to="vector_editing.vectorpath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Path Offset",
                "verbose_name_plural": "Path Offsets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BooleanOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("union", "Union"),
                            ("subtract", "Subtract"),
                            ("intersect", "Intersect"),
                            ("exclude", "Exclude"),
                            ("divide", "Divide"),
                            ("trim", "Trim"),
                            ("merge", "Merge"),
                            ("crop", "Crop"),
                            ("outline", "Outline"),
                            ("minus_back", "Minus Back"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_paths",
                    models.JSONField(help_text="Array of source path UUIDs"),
                ),
                (
                    "original_state",
                    models.JSONField(help_text="Original paths data for undo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boolean_operations",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boolean_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_path",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boolean_result",
                        to="vector_editing.vectorpath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boolean Operation",
                "verbose_name_plural": "Boolean Operations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VectorPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("user", "User Created"),
                            ("preset", "Preset"),
                            ("imported", "Imported"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("pattern_content", models.TextField()),
                ("width", models.FloatField(default=10)),
                ("height", models.FloatField(default=10)),
                ("pattern_transform", models.JSONField(default=list)),
                ("preview_url", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vector Pattern",
                "verbose_name_plural": "Vector Patterns",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="vectorpath",
            name="fill_pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vector_editing.vectorpattern",
            ),
        ),
        migrations.CreateModel(
            name="VectorShape",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "shape_type",
                    models.CharField(
                        choices=[
                            ("rectangle", "Rectangle"),
                            ("ellipse", "Ellipse"),
                            ("polygon", "Polygon"),
                            ("star", "Star"),
                            ("line", "Line"),
                            ("arrow", "Arrow"),
                            ("arc", "Arc"),
                            ("spiral", "Spiral"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("fill_color", models.CharField(default="#000000", max_length=50)),
                ("stroke_color", models.CharField(blank=True, max_length=50)),
                ("stroke_width", models.FloatField(default=1.0)),
                ("z_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_shapes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vector Shape",
                "verbose_name_plural": "Vector Shapes",
                "ordering": ["z_index"],
            },
        ),
    ]
