# Generated by Django 5.2.7 on 2025-11-13 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("svg", "SVG"),
                            ("pdf", "PDF"),
                            ("png", "PNG"),
                            ("figma", "Figma JSON"),
                        ],
                        default="svg",
                        max_length=10,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("ultra", "Ultra"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                ("optimize", models.BooleanField(default=True)),
                ("include_metadata", models.BooleanField(default=False)),
                ("compression", models.CharField(default="medium", max_length=10)),
                (
                    "width",
                    models.IntegerField(
                        blank=True,
                        help_text="Custom width (null = original)",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True,
                        help_text="Custom height (null = original)",
                        null=True,
                    ),
                ),
                (
                    "scale",
                    models.FloatField(
                        default=1.0, help_text="Scale factor (1.0 = 100%)"
                    ),
                ),
                ("format_options", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("format", models.CharField(default="svg", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_projects", models.IntegerField(default=0)),
                ("completed_projects", models.IntegerField(default=0)),
                ("failed_projects", models.IntegerField(default=0)),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="exports/%Y/%m/%d/"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="export_jobs", to="projects.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.exporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
