# Generated by Django 5.2.8 on 2025-11-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_assetcollection_assetcomment_assetversion"),
        ("projects", "0002_exporttemplate_exportjob"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("description", models.TextField(blank=True)),
                ("project_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ABTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "traffic_percentage",
                    models.IntegerField(
                        default=100,
                        help_text="Percentage of visitors to include in test",
                    ),
                ),
                (
                    "primary_goal",
                    models.CharField(
                        choices=[
                            ("clicks", "Clicks"),
                            ("conversions", "Conversions"),
                            ("engagement_time", "Engagement Time"),
                            ("scroll_depth", "Scroll Depth"),
                        ],
                        default="clicks",
                        max_length=100,
                    ),
                ),
                ("goals", models.JSONField(default=list)),
                ("target_audience", models.JSONField(blank=True, default=dict)),
                (
                    "min_sample_size",
                    models.IntegerField(
                        default=100, help_text="Minimum sample size per variant"
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=95.0, help_text="Required confidence level (0-100)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_tests",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ABTestVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("design_data", models.JSONField(default=dict)),
                (
                    "traffic_percentage",
                    models.IntegerField(
                        default=50, help_text="Traffic percentage for this variant"
                    ),
                ),
                ("is_control", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="projects.abtest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ABTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impressions", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                (
                    "total_engagement_time",
                    models.IntegerField(default=0, help_text="Total time in seconds"),
                ),
                ("click_rate", models.FloatField(default=0)),
                ("conversion_rate", models.FloatField(default=0)),
                ("avg_engagement_time", models.FloatField(default=0)),
                (
                    "confidence_level",
                    models.FloatField(
                        default=0, help_text="Statistical confidence (0-100)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="projects.abtestvariant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="abtest",
            name="winning_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_tests",
                to="projects.abtestvariant",
            ),
        ),
        migrations.CreateModel(
            name="CodeExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("react", "React"),
                            ("react_typescript", "React TypeScript"),
                            ("vue", "Vue.js"),
                            ("html_css", "HTML/CSS"),
                            ("tailwind", "Tailwind CSS"),
                            ("styled_components", "Styled Components"),
                            ("scss", "SCSS"),
                            ("flutter", "Flutter"),
                            ("swift_ui", "SwiftUI"),
                        ],
                        default="react",
                        max_length=50,
                    ),
                ),
                ("options", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("output_code", models.TextField(blank=True)),
                ("output_files", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("lines_of_code", models.IntegerField(default=0)),
                ("components_generated", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_exports",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollaborationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("cursor_position", models.JSONField(default=dict)),
                ("selected_elements", models.JSONField(default=list)),
                ("viewport", models.JSONField(default=dict)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_sessions",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
                "unique_together": {("project", "user")},
            },
        ),
        migrations.CreateModel(
            name="DesignFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("critique", "Design Critique"),
                            ("color_suggestion", "Color Suggestions"),
                            ("typography_suggestion", "Typography Suggestions"),
                            ("layout_suggestion", "Layout Suggestions"),
                            ("accessibility", "Accessibility Check"),
                            ("brand_consistency", "Brand Consistency"),
                        ],
                        max_length=30,
                    ),
                ),
                ("feedback_data", models.JSONField(default=dict)),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("user_notes", models.TextField(blank=True)),
                ("model_used", models.CharField(default="gpt-4", max_length=50)),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "processing_time",
                    models.FloatField(default=0.0, help_text="Seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedback",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignReviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes Requested"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("require_all_approvals", models.BooleanField(default=False)),
                ("allow_anonymous_feedback", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_review_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_sessions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("colors", models.JSONField(default=dict)),
                ("typography", models.JSONField(default=dict)),
                ("spacing", models.JSONField(default=dict)),
                ("radii", models.JSONField(default=dict)),
                ("shadows", models.JSONField(default=dict)),
                ("breakpoints", models.JSONField(default=dict)),
                ("component_variants", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("is_template", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_projects",
                    models.ManyToManyField(
                        blank=True, related_name="design_systems", to="projects.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_systems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignSystemExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("css_variables", "CSS Variables"),
                            ("scss_variables", "SCSS Variables"),
                            ("tailwind_config", "Tailwind Config"),
                            ("json_tokens", "JSON Tokens"),
                            ("figma_tokens", "Figma Tokens"),
                            ("style_dictionary", "Style Dictionary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("output_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="projects.designsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("social_media", "Social Media"),
                            ("presentation", "Presentation"),
                            ("branding", "Branding"),
                            ("marketing", "Marketing"),
                            ("web", "Web Design"),
                            ("mobile", "Mobile App"),
                            ("print", "Print Design"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "preview_images",
                    models.JSONField(
                        default=list, help_text="List of preview image URLs"
                    ),
                ),
                (
                    "design_data",
                    models.JSONField(
                        default=dict, help_text="Template design structure"
                    ),
                ),
                ("canvas_width", models.IntegerField(default=1920)),
                ("canvas_height", models.IntegerField(default=1080)),
                (
                    "canvas_background",
                    models.CharField(default="#FFFFFF", max_length=50),
                ),
                ("tags", models.JSONField(default=list)),
                ("color_palette", models.JSONField(default=list)),
                ("suggested_fonts", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("favorite_count", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-use_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                ("access_token", models.CharField(max_length=64, unique=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("comment", "View & Comment"),
                            ("edit", "View & Edit"),
                            ("full", "Full Access"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("password_protected", models.BooleanField(default=False)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                ("max_views", models.IntegerField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("allow_download", models.BooleanField(default=False)),
                ("allow_copy", models.BooleanField(default=False)),
                ("watermark_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_accesses",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_guest_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_accesses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Guest accesses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("download", "Downloaded"),
                            ("comment", "Commented"),
                            ("edit", "Edited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("event_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="projects.guestaccess",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HandoffAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("spec", "Specification"),
                            ("question", "Question"),
                            ("requirement", "Requirement"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("target_element_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff_annotations",
                        to="projects.project",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changes", models.JSONField(default=list)),
                ("last_known_version", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("completed", "Completed"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("conflicts", models.JSONField(default=list)),
                ("resolved_changes", models.JSONField(default=list)),
                ("device_id", models.CharField(max_length=255)),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("client_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_syncs",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_syncs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tools", "Tools"),
                            ("effects", "Effects"),
                            ("integrations", "Integrations"),
                            ("ai", "AI & Automation"),
                            ("export", "Export"),
                            ("collaboration", "Collaboration"),
                            ("analytics", "Analytics"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("changelog", models.TextField(blank=True)),
                (
                    "entry_point",
                    models.CharField(
                        help_text="Main function/class name", max_length=255
                    ),
                ),
                (
                    "source_code",
                    models.TextField(
                        blank=True,
                        help_text="Plugin source code (for sandboxed execution)",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="External source URL"),
                ),
                (
                    "hooks",
                    models.JSONField(
                        default=list, help_text="List of hooks this plugin uses"
                    ),
                ),
                (
                    "api_version",
                    models.CharField(
                        default="1.0",
                        help_text="Minimum API version required",
                        max_length=20,
                    ),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        default=dict, help_text="JSON Schema for plugin configuration"
                    ),
                ),
                ("permissions", models.JSONField(default=list)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="plugins/icons/"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="plugins/banners/"
                    ),
                ),
                ("screenshots", models.JSONField(default=list)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_free", models.BooleanField(default=True)),
                ("installs", models.IntegerField(default=0)),
                ("rating_average", models.FloatField(default=0)),
                ("rating_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("published", "Published"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_official", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_plugins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-installs"],
            },
        ),
        migrations.CreateModel(
            name="ReviewSessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                ("guest_name", models.CharField(blank=True, max_length=255)),
                ("invite_token", models.CharField(blank=True, max_length=64)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("approver", "Approver"),
                            ("reviewer", "Reviewer"),
                            ("viewer", "Viewer"),
                        ],
                        default="reviewer",
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("approved_with_comments", "Approved with Comments"),
                            ("changes_requested", "Changes Requested"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("is_notified", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="projects.designreviewsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "user", "guest_email")},
            },
        ),
        migrations.CreateModel(
            name="ReviewAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("pin", "Pin Comment"),
                            ("area", "Area Selection"),
                            ("arrow", "Arrow"),
                            ("drawing", "Freehand Drawing"),
                        ],
                        default="pin",
                        max_length=20,
                    ),
                ),
                ("position_data", models.JSONField(default=dict)),
                ("comment", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="projects.reviewannotation",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="projects.designreviewsession",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="projects.reviewsessionparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("keyboard_shortcuts", models.JSONField(default=dict)),
                ("auto_save", models.BooleanField(default=True)),
                (
                    "auto_save_interval",
                    models.IntegerField(
                        default=30, help_text="Seconds between auto-saves"
                    ),
                ),
                ("canvas_grid", models.BooleanField(default=True)),
                ("snap_to_grid", models.BooleanField(default=True)),
                ("grid_size", models.IntegerField(default=10)),
                (
                    "default_export_format",
                    models.CharField(default="png", max_length=20),
                ),
                ("notification_email", models.BooleanField(default=True)),
                ("notification_push", models.BooleanField(default=True)),
                ("notification_sound", models.BooleanField(default=True)),
                (
                    "offline_mode",
                    models.BooleanField(
                        default=True, help_text="Enable offline mode support"
                    ),
                ),
                ("offline_projects", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoConferenceRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("room_code", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.IntegerField(default=10)),
                ("is_recording_enabled", models.BooleanField(default=False)),
                ("is_screen_share_enabled", models.BooleanField(default=True)),
                ("is_canvas_sync_enabled", models.BooleanField(default=True)),
                ("waiting_room_enabled", models.BooleanField(default=True)),
                ("external_provider", models.CharField(blank=True, max_length=50)),
                ("external_room_id", models.CharField(blank=True, max_length=255)),
                ("external_join_url", models.URLField(blank=True)),
                ("recording_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_conferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_conferences",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_conferences",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="ABTestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("impression", "Impression"),
                            ("click", "Click"),
                            ("conversion", "Conversion"),
                            ("engagement", "Engagement"),
                            ("scroll", "Scroll"),
                            ("hover", "Hover"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visitor_id", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=255)),
                ("event_data", models.JSONField(default=dict)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("referrer", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="projects.abtestvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["variant", "event_type"],
                        name="projects_ab_variant_a76a39_idx",
                    ),
                    models.Index(
                        fields=["visitor_id"], name="projects_ab_visitor_2e858e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CollaborationPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255)),
                ("cursor_x", models.FloatField(blank=True, null=True)),
                ("cursor_y", models.FloatField(blank=True, null=True)),
                ("selected_elements", models.JSONField(default=list)),
                ("activity_status", models.CharField(default="active", max_length=50)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("last_heartbeat", models.DateTimeField(auto_now=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "project", "session_id")},
            },
        ),
        migrations.CreateModel(
            name="CanvasEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edit_type",
                    models.CharField(
                        choices=[
                            ("create", "Create Element"),
                            ("update", "Update Element"),
                            ("delete", "Delete Element"),
                            ("move", "Move Element"),
                            ("resize", "Resize Element"),
                            ("style", "Style Change"),
                            ("group", "Group Elements"),
                            ("ungroup", "Ungroup Elements"),
                        ],
                        max_length=20,
                    ),
                ),
                ("element_id", models.CharField(blank=True, max_length=100)),
                ("previous_data", models.JSONField(default=dict)),
                ("new_data", models.JSONField(default=dict)),
                ("vector_clock", models.JSONField(default=dict)),
                ("parent_edit_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canvas_edits",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.collaborationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="projects_ca_project_1fc596_idx",
                    ),
                    models.Index(
                        fields=["element_id"], name="projects_ca_element_923449_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("anchor_position", models.JSONField(blank=True, null=True)),
                ("anchor_element_id", models.CharField(blank=True, max_length=100)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentioned_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentioned_in_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="projects.comment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.project",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="projects_co_project_6e0434_idx",
                    ),
                    models.Index(
                        fields=["is_resolved"], name="projects_co_is_reso_2a5270_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponentSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("element_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("dimensions", models.JSONField(default=dict)),
                ("styles", models.JSONField(default=dict)),
                ("responsive_variants", models.JSONField(default=dict)),
                ("states", models.JSONField(default=dict)),
                ("props", models.JSONField(default=list)),
                ("assets", models.JSONField(default=list)),
                ("code_snippets", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_specs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("project", "element_id")},
            },
        ),
        migrations.CreateModel(
            name="PluginInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed_version", models.CharField(max_length=50)),
                ("config", models.JSONField(default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="projects.plugin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_plugins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-installed_at"],
                "unique_together": {("user", "plugin")},
            },
        ),
        migrations.CreateModel(
            name="PluginReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("review", models.TextField()),
                ("is_verified_install", models.BooleanField(default=False)),
                ("helpful_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="projects.plugin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("plugin", "user")},
            },
        ),
        migrations.CreateModel(
            name="ProjectTagAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_associations",
                        to="projects.project",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_associations",
                        to="projects.projecttag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("project", "tag")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes Requested"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "design_quality",
                    models.IntegerField(blank=True, help_text="1-10 rating", null=True),
                ),
                (
                    "creativity",
                    models.IntegerField(blank=True, help_text="1-10 rating", null=True),
                ),
                (
                    "usability",
                    models.IntegerField(blank=True, help_text="1-10 rating", null=True),
                ),
                (
                    "overall_rating",
                    models.IntegerField(blank=True, help_text="1-10 rating", null=True),
                ),
                ("reviewed_version", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("project", "reviewer")},
            },
        ),
        migrations.CreateModel(
            name="TemplateFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="projects.designtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "template")},
            },
        ),
        migrations.CreateModel(
            name="TemplateRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="projects.designtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "template")},
            },
        ),
        migrations.CreateModel(
            name="VideoConferenceParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("co-host", "Co-host"),
                            ("presenter", "Presenter"),
                            ("participant", "Participant"),
                            ("viewer", "Viewer"),
                        ],
                        default="participant",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("can_share_screen", models.BooleanField(default=True)),
                ("can_annotate", models.BooleanField(default=True)),
                ("can_edit_canvas", models.BooleanField(default=False)),
                ("connection_quality", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="projects.videoconferenceroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "user")},
            },
        ),
    ]
