# Generated by Django 5.2.8 on 2025-12-01 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projecttag_abtest_abtestvariant_abtestresult_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "version_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label like 'v1.0', 'Final', 'Before refactor'",
                        max_length=100,
                    ),
                ),
                (
                    "design_data",
                    models.JSONField(help_text="Complete design state at this version"),
                ),
                (
                    "canvas_settings",
                    models.JSONField(
                        default=dict,
                        help_text="Canvas width, height, background at this version",
                    ),
                ),
                ("components_count", models.IntegerField(default=0)),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of design_data for quick comparison",
                        max_length=64,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="version_thumbnails/%Y/%m/"
                    ),
                ),
                (
                    "data_size_bytes",
                    models.IntegerField(
                        default=0, help_text="Size of design_data in bytes"
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated or user-provided summary of changes",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Save"),
                            ("auto", "Auto Save"),
                            ("restore", "Restored Version"),
                            ("branch", "Branched Version"),
                            ("merge", "Merged Version"),
                            ("ai_generated", "AI Generated"),
                            ("import", "Imported"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        default="main",
                        help_text="Branch name for this version",
                        max_length=100,
                    ),
                ),
                (
                    "is_branch_head",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the latest version in its branch?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_snapshots",
                        to="projects.projectsnapshot",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="VersionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "component_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of component being commented on",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.projectsnapshot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VersionDiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diff_data",
                    models.JSONField(help_text="Structured diff information"),
                ),
                ("components_added", models.IntegerField(default=0)),
                ("components_removed", models.IntegerField(default=0)),
                ("components_modified", models.IntegerField(default=0)),
                ("properties_changed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_from",
                        to="projects.projectsnapshot",
                    ),
                ),
                (
                    "to_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_to",
                        to="projects.projectsnapshot",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="projectsnapshot",
            index=models.Index(
                fields=["project", "branch_name", "-version_number"],
                name="projects_pr_project_5dd273_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectsnapshot",
            index=models.Index(
                fields=["content_hash"], name="projects_pr_content_4fc470_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectsnapshot",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="projects_pr_created_ab72ed_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectsnapshot",
            unique_together={("project", "version_number")},
        ),
        migrations.AlterUniqueTogether(
            name="versiondiff",
            unique_together={("from_snapshot", "to_snapshot")},
        ),
    ]
