# Generated by Django 5.2.8 on 2025-12-01 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectsnapshot_versioncomment_versiondiff_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortcutCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Shortcut categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BatchOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("move", "Move"),
                            ("resize", "Resize"),
                            ("style", "Style Change"),
                            ("delete", "Delete"),
                            ("duplicate", "Duplicate"),
                            ("group", "Group"),
                            ("ungroup", "Ungroup"),
                            ("align", "Align"),
                            ("distribute", "Distribute"),
                            ("lock", "Lock/Unlock"),
                            ("visibility", "Show/Hide"),
                            ("order", "Change Order"),
                            ("transform", "Transform"),
                            ("replace", "Find & Replace"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("undone", "Undone"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "component_ids",
                    models.JSONField(
                        default=list,
                        help_text="IDs of components affected by this operation",
                    ),
                ),
                ("component_count", models.IntegerField(default=0)),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Operation-specific parameters"
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        default=dict, help_text="State before operation for undo"
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(default=dict, help_text="State after operation"),
                ),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_operations",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignTokenLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use as default library for new projects",
                    ),
                ),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_libraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Design Token Libraries",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Token name must be lowercase, start with a letter, and contain only letters, numbers, and hyphens",
                                regex="^[a-z][a-z0-9-]*$",
                            )
                        ],
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("color", "Color"),
                            ("spacing", "Spacing"),
                            ("sizing", "Sizing"),
                            ("typography", "Typography"),
                            ("font-family", "Font Family"),
                            ("font-size", "Font Size"),
                            ("font-weight", "Font Weight"),
                            ("line-height", "Line Height"),
                            ("border-radius", "Border Radius"),
                            ("border-width", "Border Width"),
                            ("shadow", "Shadow"),
                            ("opacity", "Opacity"),
                            ("z-index", "Z-Index"),
                            ("breakpoint", "Breakpoint"),
                            ("duration", "Duration"),
                            ("easing", "Easing"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                ("css_variable", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "usage_examples",
                    models.JSONField(
                        default=list, help_text="Example use cases for this token"
                    ),
                ),
                ("deprecated", models.BooleanField(default=False)),
                ("deprecated_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "references",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference another token for aliasing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referenced_by",
                        to="projects.designtoken",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="projects.designtokenlibrary",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
                "unique_together": {("library", "name")},
            },
        ),
        migrations.CreateModel(
            name="DesignTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "theme_type",
                    models.CharField(
                        choices=[
                            ("color-scheme", "Color Scheme"),
                            ("brand", "Brand Variation"),
                            ("density", "Density"),
                            ("accessibility", "Accessibility"),
                            ("custom", "Custom"),
                        ],
                        default="color-scheme",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "css_selector",
                    models.CharField(
                        blank=True,
                        help_text="CSS selector for this theme (e.g., [data-theme='dark'])",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extends",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="projects.designtheme",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="projects.designtokenlibrary",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("library", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ExportPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("png", "PNG"),
                            ("jpg", "JPEG"),
                            ("svg", "SVG"),
                            ("pdf", "PDF"),
                            ("webp", "WebP"),
                            ("gif", "GIF"),
                            ("ico", "ICO"),
                        ],
                        default="png",
                        max_length=10,
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        choices=[
                            ("0.5x", "0.5x"),
                            ("1x", "1x"),
                            ("1.5x", "1.5x"),
                            ("2x", "2x"),
                            ("3x", "3x"),
                            ("4x", "4x"),
                        ],
                        default="1x",
                        max_length=10,
                    ),
                ),
                ("quality", models.IntegerField(default=90)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("maintain_aspect_ratio", models.BooleanField(default=True)),
                ("include_background", models.BooleanField(default=True)),
                ("flatten_layers", models.BooleanField(default=False)),
                ("optimize_for_web", models.BooleanField(default=True)),
                (
                    "file_naming_pattern",
                    models.CharField(
                        default="{name}_{scale}",
                        help_text="Variables: {name}, {scale}, {format}, {date}, {time}, {index}",
                        max_length=255,
                    ),
                ),
                ("create_subfolder", models.BooleanField(default=False)),
                (
                    "subfolder_pattern",
                    models.CharField(default="{format}_{scale}", max_length=255),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="ExportPresetBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                            ("desktop", "Desktop"),
                            ("social", "Social Media"),
                            ("print", "Print"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "presets",
                    models.ManyToManyField(
                        related_name="bundles", to="projects.exportpreset"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LearningModeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("show_hints", models.BooleanField(default=True)),
                ("learning_categories", models.JSONField(default=list)),
                ("daily_goal", models.IntegerField(default=10)),
                ("shortcuts_learned", models.JSONField(default=list)),
                ("current_streak", models.IntegerField(default=0)),
                ("best_streak", models.IntegerField(default=0)),
                ("last_practice_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcut_learning_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("once", "One-time"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("on_change", "On Change"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.IntegerField(default=0)),
                ("export_all", models.BooleanField(default=True)),
                ("component_ids", models.JSONField(default=list)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("download", "Download Link"),
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                            ("s3", "S3 Bucket"),
                            ("dropbox", "Dropbox"),
                            ("gdrive", "Google Drive"),
                        ],
                        default="download",
                        max_length=20,
                    ),
                ),
                ("delivery_config", models.JSONField(default=dict)),
                ("retry_on_failure", models.BooleanField(default=True)),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.exportpresetbundle",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.exportpreset",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_exports",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("format", models.CharField(max_length=10)),
                ("component_count", models.IntegerField(default=0)),
                ("file_count", models.IntegerField(default=0)),
                ("total_size", models.BigIntegerField(default=0)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("download_url", models.URLField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_history",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.exportpreset",
                    ),
                ),
                (
                    "scheduled_export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="projects.scheduledexport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Export histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KeyboardShortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("tool", "Select Tool"),
                            ("action", "Perform Action"),
                            ("view", "Change View"),
                            ("panel", "Toggle Panel"),
                            ("zoom", "Zoom Control"),
                            ("edit", "Edit Operation"),
                            ("file", "File Operation"),
                            ("layer", "Layer Operation"),
                            ("align", "Alignment"),
                            ("transform", "Transform"),
                            ("history", "History"),
                            ("custom", "Custom"),
                        ],
                        default="action",
                        max_length=20,
                    ),
                ),
                ("default_key", models.CharField(max_length=50)),
                ("default_key_mac", models.CharField(blank=True, max_length=50)),
                ("default_key_windows", models.CharField(blank=True, max_length=50)),
                ("default_key_linux", models.CharField(blank=True, max_length=50)),
                ("is_system", models.BooleanField(default=True)),
                ("is_customizable", models.BooleanField(default=True)),
                ("requires_selection", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shortcuts",
                        to="projects.shortcutcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShortcutPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "preset_type",
                    models.CharField(
                        choices=[
                            ("system", "System Preset"),
                            ("app", "Application Preset"),
                            ("user", "User Preset"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("mappings", models.JSONField(default=dict)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_default", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcut_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["preset_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShortcutUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_shortcut", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "shortcut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="projects.keyboardshortcut",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcut_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TokenChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("rename", "Renamed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=500)),
                ("new_value", models.CharField(blank=True, max_length=500)),
                ("library_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="projects.designtokenlibrary",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="projects.designtoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="projects.designtokenlibrary",
                    ),
                ),
                (
                    "tokens",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="projects.designtoken"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTokenBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_overrides",
                    models.JSONField(
                        default=dict, help_text="Project-specific token overrides"
                    ),
                ),
                ("is_synced", models.BooleanField(default=True)),
                ("last_synced", models.DateTimeField(auto_now_add=True)),
                ("sync_errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_bindings",
                        to="projects.designtokenlibrary",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_bindings",
                        to="projects.project",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_bindings",
                        to="projects.designtheme",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "library")},
            },
        ),
        migrations.CreateModel(
            name="ThemeTokenOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="projects.designtheme",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_overrides",
                        to="projects.designtoken",
                    ),
                ),
            ],
            options={
                "unique_together": {("theme", "token")},
            },
        ),
        migrations.CreateModel(
            name="TokenExportFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("css", "CSS Variables"),
                            ("scss", "SCSS Variables"),
                            ("less", "LESS Variables"),
                            ("json", "JSON"),
                            ("js", "JavaScript Module"),
                            ("ts", "TypeScript Module"),
                            ("swift", "Swift"),
                            ("kotlin", "Kotlin"),
                            ("tailwind", "Tailwind Config"),
                            ("figma", "Figma Tokens"),
                            ("style-dictionary", "Style Dictionary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Format-specific configuration options"
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        blank=True,
                        help_text="Custom template for export (uses Jinja2 syntax)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_formats",
                        to="projects.designtokenlibrary",
                    ),
                ),
            ],
            options={
                "unique_together": {("library", "format_type")},
            },
        ),
        migrations.CreateModel(
            name="UserShortcutOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_key", models.CharField(max_length=50)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shortcut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="projects.keyboardshortcut",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcut_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "shortcut")},
            },
        ),
    ]
