# Generated by Django 5.2.11 on 2026-02-27 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_batchoperation_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="designtemplate",
            index=models.Index(
                fields=["category", "-use_count"], name="projects_de_categor_2d68e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designtemplate",
            index=models.Index(
                fields=["is_public", "is_premium", "-use_count"],
                name="projects_de_is_publ_846fa1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="designtemplate",
            index=models.Index(
                fields=["is_featured", "-created_at"],
                name="projects_de_is_feat_ffa42d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "-updated_at"], name="projects_pr_user_id_5d1716_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "project_type"], name="projects_pr_user_id_12f247_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_public", "-updated_at"],
                name="projects_pr_is_publ_9413e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["-created_at"], name="projects_pr_created_775fe7_idx"
            ),
        ),
    ]
