# Generated by Django 5.2.11 on 2026-02-28 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_designtemplate_projects_de_categor_2d68e5_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productivity_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
