# Generated by Django 5.2.8 on 2025-12-01 18:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_coupon_creatorprofile_marketplacetemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "input_cost_per_1k",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "output_cost_per_1k",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "cost_per_image",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=4096, help_text="Maximum context length"
                    ),
                ),
                ("supports_images", models.BooleanField(default=False)),
                ("supports_vision", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Model Pricing",
                "verbose_name_plural": "AI Model Pricing",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="First day of the billing period"),
                ),
                (
                    "period_end",
                    models.DateField(help_text="Last day of the billing period"),
                ),
                ("ai_requests_used", models.IntegerField(default=0)),
                ("ai_tokens_used", models.BigIntegerField(default=0)),
                ("image_generations_used", models.IntegerField(default=0)),
                (
                    "ai_requests_limit",
                    models.IntegerField(
                        default=10,
                        help_text="Max AI requests per period, -1 for unlimited",
                    ),
                ),
                (
                    "ai_tokens_limit",
                    models.BigIntegerField(
                        default=10000,
                        help_text="Max tokens per period, -1 for unlimited",
                    ),
                ),
                (
                    "image_generations_limit",
                    models.IntegerField(
                        default=3,
                        help_text="Max image generations per period, -1 for unlimited",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Budget limit in USD, 0 for no limit",
                        max_digits=10,
                    ),
                ),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("layout_generation", "Layout Generation"),
                            ("logo_generation", "Logo Generation"),
                            ("color_palette", "Color Palette"),
                            ("font_suggestion", "Font Suggestion"),
                            ("design_refinement", "Design Refinement"),
                            ("image_generation", "Image Generation"),
                            ("design_critique", "Design Critique"),
                            ("typography_suggestion", "Typography Suggestion"),
                            ("layout_optimization", "Layout Optimization"),
                            ("trend_analysis", "Trend Analysis"),
                            ("improvement_suggestions", "Improvement Suggestions"),
                            ("image_to_design", "Image to Design"),
                            ("style_transfer", "Style Transfer"),
                            ("voice_to_design", "Voice to Design"),
                            ("accessibility_check", "Accessibility Check"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="AI model used (e.g., gpt-4-turbo, dall-e-3)",
                        max_length=50,
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("images_generated", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Request latency in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "project_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Related project ID if applicable",
                        null=True,
                    ),
                ),
                (
                    "prompt_preview",
                    models.CharField(
                        blank=True,
                        help_text="First 200 chars of prompt for reference",
                        max_length=200,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the request",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quota",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="subscriptions.aiusagequota",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Usage Threshold"),
                            ("daily_limit", "Daily Spending Limit"),
                            ("weekly_limit", "Weekly Spending Limit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold_percent",
                    models.IntegerField(
                        blank=True,
                        help_text="Alert when usage reaches this percentage (1-100)",
                        null=True,
                    ),
                ),
                (
                    "spending_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Spending limit in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["threshold_percent", "spending_limit"],
            },
        ),
        migrations.AddIndex(
            model_name="aiusagequota",
            index=models.Index(
                fields=["user", "period_start"], name="subscriptio_user_id_7343db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagequota",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="subscriptio_period__728f78_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiusagequota",
            unique_together={("user", "period_start")},
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["user", "-created_at"], name="subscriptio_user_id_9d6ae5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["request_type", "-created_at"],
                name="subscriptio_request_399367_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["model", "-created_at"], name="subscriptio_model_0b443d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["success", "-created_at"], name="subscriptio_success_259bd6_idx"
            ),
        ),
    ]
