# Generated by Django 5.2.10 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkupTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("mappings", models.JSONField(default=list)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markup_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="pdfs/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("page_count", models.IntegerField(default=0)),
                ("file_size", models.BigIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("keywords", models.TextField(blank=True)),
                ("creator", models.CharField(blank=True, max_length=255)),
                ("producer", models.CharField(blank=True, max_length=255)),
                ("creation_date", models.DateTimeField(blank=True, null=True)),
                ("modification_date", models.DateTimeField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_documents",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0)),
                ("annotations_found", models.IntegerField(default=0)),
                ("annotations_imported", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_import_jobs",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="pdf_annotation.pdfdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("settings", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0)),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="pdf_exports/"),
                ),
                ("page_count", models.IntegerField(default=0)),
                ("file_size", models.BigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_exports",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_number", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pdf_pages/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="pdf_thumbnails/"
                    ),
                ),
                ("width", models.FloatField(default=0)),
                ("height", models.FloatField(default=0)),
                ("rotation", models.IntegerField(default=0)),
                ("text_content", models.TextField(blank=True)),
                ("text_blocks", models.JSONField(default=list)),
                ("annotation_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="pdf_annotation.pdfdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
                "unique_together": {("document", "page_number")},
            },
        ),
        migrations.CreateModel(
            name="PDFAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("highlight", "Highlight"),
                            ("underline", "Underline"),
                            ("strikeout", "Strikeout"),
                            ("squiggly", "Squiggly"),
                            ("text", "Text Note"),
                            ("freetext", "Free Text"),
                            ("line", "Line"),
                            ("arrow", "Arrow"),
                            ("rectangle", "Rectangle"),
                            ("circle", "Circle"),
                            ("polygon", "Polygon"),
                            ("polyline", "Polyline"),
                            ("ink", "Ink/Freehand"),
                            ("stamp", "Stamp"),
                            ("caret", "Caret"),
                            ("link", "Link"),
                            ("file_attachment", "File Attachment"),
                            ("sound", "Sound"),
                        ],
                        max_length=20,
                    ),
                ),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("width", models.FloatField(default=0)),
                ("height", models.FloatField(default=0)),
                ("content", models.TextField(blank=True)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("opacity", models.FloatField(default=1.0)),
                ("border_width", models.FloatField(default=1.0)),
                ("vertices", models.JSONField(default=list)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("creation_date", models.DateTimeField(blank=True, null=True)),
                ("modification_date", models.DateTimeField(blank=True, null=True)),
                ("rich_content", models.TextField(blank=True)),
                ("covered_text", models.TextField(blank=True)),
                ("quads", models.JSONField(default=list)),
                ("imported_to_design", models.BooleanField(default=False)),
                ("design_element_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="pdf_annotation.pdfpage",
                    ),
                ),
            ],
            options={
                "ordering": ["page__page_number", "y", "x"],
            },
        ),
    ]
