# Generated by Django 5.2.10 on 2026-01-28 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_annotation", "0001_initial"),
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfexport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdf_annotation_exports",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="pdfexport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdf_annotation_exports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
