# Generated by Django 5.2.10 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("navigation", "Navigation"),
                            ("form", "Form Elements"),
                            ("media", "Media"),
                            ("content", "Content Display"),
                            ("feedback", "Feedback"),
                            ("overlay", "Overlays"),
                            ("commerce", "E-Commerce"),
                            ("social", "Social Media"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("dropdown", "Dropdown Menu"),
                            ("carousel", "Carousel/Slider"),
                            ("accordion", "Accordion"),
                            ("tabs", "Tab Container"),
                            ("modal", "Modal/Dialog"),
                            ("tooltip", "Tooltip"),
                            ("popover", "Popover"),
                            ("drawer", "Drawer/Sidebar"),
                            ("toggle", "Toggle Switch"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio Button Group"),
                            ("input", "Input Field"),
                            ("select", "Select/Combobox"),
                            ("date_picker", "Date Picker"),
                            ("slider", "Range Slider"),
                            ("progress", "Progress Bar"),
                            ("stepper", "Stepper/Wizard"),
                            ("pagination", "Pagination"),
                            ("video_player", "Video Player"),
                            ("audio_player", "Audio Player"),
                            ("custom", "Custom Interactive"),
                        ],
                        max_length=30,
                    ),
                ),
                ("template_data", models.JSONField()),
                ("preview_image", models.URLField(blank=True)),
                ("preview_animation", models.URLField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("is_premium", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="InteractiveComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("dropdown", "Dropdown Menu"),
                            ("carousel", "Carousel/Slider"),
                            ("accordion", "Accordion"),
                            ("tabs", "Tab Container"),
                            ("modal", "Modal/Dialog"),
                            ("tooltip", "Tooltip"),
                            ("popover", "Popover"),
                            ("drawer", "Drawer/Sidebar"),
                            ("toggle", "Toggle Switch"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio Button Group"),
                            ("input", "Input Field"),
                            ("select", "Select/Combobox"),
                            ("date_picker", "Date Picker"),
                            ("slider", "Range Slider"),
                            ("progress", "Progress Bar"),
                            ("stepper", "Stepper/Wizard"),
                            ("pagination", "Pagination"),
                            ("video_player", "Video Player"),
                            ("audio_player", "Audio Player"),
                            ("custom", "Custom Interactive"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("default_state", models.CharField(default="default", max_length=50)),
                ("config", models.JSONField(default=dict)),
                ("styles", models.JSONField(default=dict)),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("width", models.FloatField(default=200)),
                ("height", models.FloatField(default=100)),
                ("z_index", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactive_components",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interactive Component",
                "verbose_name_plural": "Interactive Components",
                "ordering": ["z_index"],
            },
        ),
        migrations.CreateModel(
            name="DropdownOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("is_disabled", models.BooleanField(default=False)),
                ("is_selected", models.BooleanField(default=False)),
                ("group", models.CharField(blank=True, max_length=100)),
                ("order", models.IntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        limit_choices_to={"component_type__in": ["dropdown", "select"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropdown_options",
                        to="interactive_components.interactivecomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ComponentInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("click", "On Click"),
                            ("hover", "On Hover"),
                            ("hover_end", "On Hover End"),
                            ("focus", "On Focus"),
                            ("blur", "On Blur"),
                            ("key_press", "On Key Press"),
                            ("swipe_left", "On Swipe Left"),
                            ("swipe_right", "On Swipe Right"),
                            ("swipe_up", "On Swipe Up"),
                            ("swipe_down", "On Swipe Down"),
                            ("drag", "On Drag"),
                            ("drop", "On Drop"),
                            ("scroll", "On Scroll"),
                            ("timer", "On Timer"),
                            ("value_change", "On Value Change"),
                            ("load", "On Load"),
                            ("custom", "Custom Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trigger_target", models.CharField(blank=True, max_length=100)),
                ("trigger_config", models.JSONField(default=dict)),
                ("condition", models.JSONField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("change_state", "Change State"),
                            ("toggle_state", "Toggle State"),
                            ("set_variable", "Set Variable"),
                            ("navigate", "Navigate To"),
                            ("open_url", "Open URL"),
                            ("play_animation", "Play Animation"),
                            ("stop_animation", "Stop Animation"),
                            ("show_component", "Show Component"),
                            ("hide_component", "Hide Component"),
                            ("enable", "Enable Component"),
                            ("disable", "Disable Component"),
                            ("scroll_to", "Scroll To"),
                            ("play_video", "Play Video"),
                            ("pause_video", "Pause Video"),
                            ("play_audio", "Play Audio"),
                            ("custom", "Custom Action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_config", models.JSONField(default=dict)),
                ("order", models.IntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="interactive_components.interactivecomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CarouselItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("component", "Component"),
                            ("custom", "Custom HTML"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        limit_choices_to={"component_type": "carousel"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_items",
                        to="interactive_components.interactivecomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AccordionSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.JSONField(default=dict)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("is_expanded", models.BooleanField(default=False)),
                ("is_disabled", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        limit_choices_to={"component_type": "accordion"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accordion_sections",
                        to="interactive_components.interactivecomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TabItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("content", models.JSONField(default=dict)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("badge", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("is_disabled", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        limit_choices_to={"component_type": "tabs"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tab_items",
                        to="interactive_components.interactivecomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ComponentVariable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "variable_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("array", "Array"),
                            ("object", "Object"),
                        ],
                        max_length=20,
                    ),
                ),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="interactive_components.interactivecomponent",
                    ),
                ),
            ],
            options={
                "unique_together": {("component", "name")},
            },
        ),
        migrations.CreateModel(
            name="ComponentState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("properties", models.JSONField(default=dict)),
                ("elements", models.JSONField(default=list)),
                ("enter_transition", models.JSONField(default=dict)),
                ("exit_transition", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="interactive_components.interactivecomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("component", "name")},
            },
        ),
    ]
