# Generated by Django 5.2.10 on 2026-01-28 12:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoLayoutFrame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Auto Layout Frame", max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                            ("wrap", "Wrap"),
                        ],
                        default="vertical",
                        max_length=20,
                    ),
                ),
                (
                    "primary_axis_alignment",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("center", "Center"),
                            ("end", "End"),
                            ("space-between", "Space Between"),
                            ("space-around", "Space Around"),
                            ("space-evenly", "Space Evenly"),
                        ],
                        default="start",
                        max_length=20,
                    ),
                ),
                (
                    "cross_axis_alignment",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("center", "Center"),
                            ("end", "End"),
                            ("stretch", "Stretch"),
                            ("baseline", "Baseline"),
                        ],
                        default="start",
                        max_length=20,
                    ),
                ),
                (
                    "item_spacing",
                    models.FloatField(
                        default=10.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "padding_top",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "padding_right",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "padding_bottom",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "padding_left",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "horizontal_sizing",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("hug", "Hug Contents"),
                            ("fill", "Fill Container"),
                        ],
                        default="hug",
                        max_length=20,
                    ),
                ),
                (
                    "vertical_sizing",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("hug", "Hug Contents"),
                            ("fill", "Fill Container"),
                        ],
                        default="hug",
                        max_length=20,
                    ),
                ),
                (
                    "min_width",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_width",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "overflow_horizontal",
                    models.CharField(
                        choices=[
                            ("visible", "Visible"),
                            ("hidden", "Hidden"),
                            ("scroll", "Scroll"),
                            ("auto", "Auto"),
                        ],
                        default="visible",
                        max_length=20,
                    ),
                ),
                (
                    "overflow_vertical",
                    models.CharField(
                        choices=[
                            ("visible", "Visible"),
                            ("hidden", "Hidden"),
                            ("scroll", "Scroll"),
                            ("auto", "Auto"),
                        ],
                        default="visible",
                        max_length=20,
                    ),
                ),
                ("stroke_included_in_layout", models.BooleanField(default=True)),
                (
                    "corner_radius",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "corner_radius_top_left",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "corner_radius_top_right",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "corner_radius_bottom_right",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "corner_radius_bottom_left",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "background_color",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "background_opacity",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("clip_content", models.BooleanField(default=False)),
                ("z_index", models.IntegerField(default=0)),
                ("absolute_position", models.BooleanField(default=False)),
                ("absolute_x", models.FloatField(blank=True, null=True)),
                ("absolute_y", models.FloatField(blank=True, null=True)),
                ("position_x", models.FloatField(default=0.0)),
                ("position_y", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_layout_config",
                        to="projects.designcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_auto_layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_frame",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_frames",
                        to="auto_layout.autolayoutframe",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_layout_frames",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto Layout Frame",
                "verbose_name_plural": "Auto Layout Frames",
                "ordering": ["z_index", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoLayoutChild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "horizontal_sizing",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("fill", "Fill Container"),
                            ("hug", "Hug Contents"),
                        ],
                        default="hug",
                        max_length=20,
                    ),
                ),
                (
                    "vertical_sizing",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("fill", "Fill Container"),
                            ("hug", "Hug Contents"),
                        ],
                        default="hug",
                        max_length=20,
                    ),
                ),
                (
                    "fixed_width",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fixed_height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fill_ratio",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_width",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_width",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "align_self",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (Inherit)"),
                            ("start", "Start"),
                            ("center", "Center"),
                            ("end", "End"),
                            ("stretch", "Stretch"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "flex_grow",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "flex_shrink",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_absolute", models.BooleanField(default=False)),
                ("absolute_x", models.FloatField(blank=True, null=True)),
                ("absolute_y", models.FloatField(blank=True, null=True)),
                (
                    "absolute_anchor",
                    models.CharField(
                        choices=[
                            ("top-left", "Top Left"),
                            ("top-center", "Top Center"),
                            ("top-right", "Top Right"),
                            ("center-left", "Center Left"),
                            ("center", "Center"),
                            ("center-right", "Center Right"),
                            ("bottom-left", "Bottom Left"),
                            ("bottom-center", "Bottom Center"),
                            ("bottom-right", "Bottom Right"),
                        ],
                        default="top-left",
                        max_length=20,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("rotation", models.FloatField(default=0.0)),
                ("computed_x", models.FloatField(blank=True, null=True)),
                ("computed_y", models.FloatField(blank=True, null=True)),
                ("computed_width", models.FloatField(blank=True, null=True)),
                ("computed_height", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_layout_child_config",
                        to="projects.designcomponent",
                    ),
                ),
                (
                    "parent_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="auto_layout.autolayoutframe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto Layout Child",
                "verbose_name_plural": "Auto Layout Children",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LayoutConstraint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "horizontal",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("left_right", "Left and Right"),
                            ("center", "Center"),
                            ("scale", "Scale"),
                        ],
                        default="left",
                        max_length=20,
                    ),
                ),
                (
                    "vertical",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("top_bottom", "Top and Bottom"),
                            ("center", "Center"),
                            ("scale", "Scale"),
                        ],
                        default="top",
                        max_length=20,
                    ),
                ),
                ("margin_left", models.FloatField(blank=True, null=True)),
                ("margin_right", models.FloatField(blank=True, null=True)),
                ("margin_top", models.FloatField(blank=True, null=True)),
                ("margin_bottom", models.FloatField(blank=True, null=True)),
                (
                    "percent_x",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "percent_y",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "percent_width",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "percent_height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("lock_aspect_ratio", models.BooleanField(default=False)),
                (
                    "aspect_ratio",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_constraint",
                        to="projects.designcomponent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layout Constraint",
                "verbose_name_plural": "Layout Constraints",
            },
        ),
        migrations.CreateModel(
            name="LayoutPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("navigation", "Navigation"),
                            ("cards", "Cards"),
                            ("lists", "Lists"),
                            ("grids", "Grids"),
                            ("forms", "Forms"),
                            ("headers", "Headers"),
                            ("footers", "Footers"),
                            ("sidebars", "Sidebars"),
                            ("modals", "Modals"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="layout_presets/"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Layout Preset",
                "verbose_name_plural": "Layout Presets",
                "ordering": ["-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResponsiveBreakpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("tablet", "Tablet"),
                            ("mobile", "Mobile"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "min_width",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "max_width",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("canvas_width", models.IntegerField(default=1920)),
                ("canvas_height", models.IntegerField(default=1080)),
                ("scale", models.FloatField(default=1.0)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsive_breakpoints",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsive Breakpoint",
                "verbose_name_plural": "Responsive Breakpoints",
                "ordering": ["-min_width"],
            },
        ),
        migrations.CreateModel(
            name="ResponsiveOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                            ("wrap", "Wrap"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("item_spacing", models.FloatField(blank=True, null=True)),
                ("padding_top", models.FloatField(blank=True, null=True)),
                ("padding_right", models.FloatField(blank=True, null=True)),
                ("padding_bottom", models.FloatField(blank=True, null=True)),
                ("padding_left", models.FloatField(blank=True, null=True)),
                (
                    "primary_axis_alignment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("start", "Start"),
                            ("center", "Center"),
                            ("end", "End"),
                            ("space-between", "Space Between"),
                            ("space-around", "Space Around"),
                            ("space-evenly", "Space Evenly"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cross_axis_alignment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("start", "Start"),
                            ("center", "Center"),
                            ("end", "End"),
                            ("stretch", "Stretch"),
                            ("baseline", "Baseline"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "horizontal_sizing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed"),
                            ("hug", "Hug Contents"),
                            ("fill", "Fill Container"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "vertical_sizing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed"),
                            ("hug", "Hug Contents"),
                            ("fill", "Fill Container"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breakpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_overrides",
                        to="auto_layout.responsivebreakpoint",
                    ),
                ),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsive_overrides",
                        to="auto_layout.autolayoutframe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsive Override",
                "verbose_name_plural": "Responsive Overrides",
                "unique_together": {("frame", "breakpoint")},
            },
        ),
    ]
