# Generated by Django 6.0 on 2026-03-02 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_systems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("approved", "Approved"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="component_previews/"
                    ),
                ),
                ("figma_node_id", models.CharField(blank=True, max_length=255)),
                ("storybook_path", models.CharField(blank=True, max_length=255)),
                ("variants", models.JSONField(default=list)),
                ("props", models.JSONField(default=list)),
                ("slots", models.JSONField(default=list)),
                ("html_template", models.TextField(blank=True)),
                ("react_template", models.TextField(blank=True)),
                ("vue_template", models.TextField(blank=True)),
                ("angular_template", models.TextField(blank=True)),
                ("specs", models.JSONField(default=dict)),
                ("anatomy", models.JSONField(default=dict)),
                ("usage_guidelines", models.TextField(blank=True)),
                ("dos", models.JSONField(default=list)),
                ("donts", models.JSONField(default=list)),
                ("accessibility_guidelines", models.TextField(blank=True)),
                ("aria_attributes", models.JSONField(default=dict)),
                ("tags", models.JSONField(default=list)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "related_components",
                    models.ManyToManyField(
                        blank=True, to="design_systems.componentdefinition"
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComponentVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("props", models.JSONField(default=dict)),
                ("tokens", models.JSONField(default=dict)),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="variant_previews/"
                    ),
                ),
                ("code_example", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_instances",
                        to="design_systems.componentdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DesignSystemExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Style Guide"),
                            ("web", "Static Website"),
                            ("figma", "Figma Library"),
                            ("sketch", "Sketch Library"),
                            ("css", "CSS Variables"),
                            ("scss", "SCSS Variables"),
                            ("json", "JSON Tokens"),
                            ("js", "JavaScript/TypeScript"),
                            ("ios", "iOS Swift"),
                            ("android", "Android XML"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="design_system_exports/"
                    ),
                ),
                ("output_url", models.URLField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignSystemSync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("figma", "Figma"),
                            ("storybook", "Storybook"),
                            ("sketch", "Sketch"),
                            ("manual", "Manual Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("direction", models.CharField(default="pull", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("changes_summary", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_history",
                        to="design_systems.designsystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design System Sync",
                "verbose_name_plural": "Design System Syncs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StyleGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand_overview", models.TextField(blank=True)),
                ("brand_values", models.JSONField(default=list)),
                ("tone_of_voice", models.TextField(blank=True)),
                ("logo_guidelines", models.TextField(blank=True)),
                ("logo_variations", models.JSONField(default=list)),
                ("logo_clearspace", models.JSONField(default=dict)),
                ("logo_misuse", models.JSONField(default=list)),
                ("color_guidelines", models.TextField(blank=True)),
                ("color_accessibility", models.TextField(blank=True)),
                ("typography_guidelines", models.TextField(blank=True)),
                ("typography_scale", models.JSONField(default=dict)),
                ("imagery_guidelines", models.TextField(blank=True)),
                ("photography_style", models.TextField(blank=True)),
                ("illustration_style", models.TextField(blank=True)),
                ("iconography_guidelines", models.TextField(blank=True)),
                ("layout_guidelines", models.TextField(blank=True)),
                ("grid_system", models.JSONField(default=dict)),
                ("spacing_guidelines", models.TextField(blank=True)),
                ("motion_guidelines", models.TextField(blank=True)),
                ("animation_principles", models.JSONField(default=list)),
                ("custom_sections", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_guide",
                        to="design_systems.designsystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Style Guide",
                "verbose_name_plural": "Style Guides",
            },
        ),
        migrations.CreateModel(
            name="DesignToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("color", "Color"),
                            ("typography", "Typography"),
                            ("spacing", "Spacing"),
                            ("sizing", "Sizing"),
                            ("border-radius", "Border Radius"),
                            ("border-width", "Border Width"),
                            ("shadow", "Shadow"),
                            ("opacity", "Opacity"),
                            ("z-index", "Z-Index"),
                            ("duration", "Duration"),
                            ("easing", "Easing"),
                            ("font-family", "Font Family"),
                            ("font-weight", "Font Weight"),
                            ("line-height", "Line Height"),
                            ("letter-spacing", "Letter Spacing"),
                            ("breakpoint", "Breakpoint"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True)),
                ("usage_guidelines", models.TextField(blank=True)),
                ("group", models.CharField(blank=True, max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("is_deprecated", models.BooleanField(default=False)),
                ("deprecated_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="references",
                        to="design_systems.designtoken",
                    ),
                ),
                (
                    "replacement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="design_systems.designtoken",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "group", "order", "name"],
                "unique_together": {("design_system", "name")},
            },
        ),
        migrations.CreateModel(
            name="DocumentationPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("content", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentation_pages",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="design_systems.documentationpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
                "unique_together": {("design_system", "slug")},
            },
        ),
    ]
