# Generated by Django 5.2.11 on 2026-02-28 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_id",
                    models.IntegerField(
                        help_text="Reference to the design project UI/UX layout"
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(
                        help_text="e.g., 'my-portfolio' for my-portfolio.designco.site",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Deploying"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "deployment_id",
                    models.CharField(
                        blank=True,
                        help_text="Vercel/Netlify deployment ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "published_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                ("error_logs", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
