# Generated by Django 5.2.10 on 2026-01-28 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "branch_type",
                    models.CharField(
                        choices=[
                            ("main", "Main"),
                            ("feature", "Feature"),
                            ("experiment", "Experiment"),
                            ("hotfix", "Hotfix"),
                            ("review", "Review"),
                        ],
                        default="feature",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_protected", models.BooleanField(default=False)),
                ("require_review", models.BooleanField(default=False)),
                ("required_reviewers", models.IntegerField(default=0)),
                ("color", models.CharField(default="#6366f1", max_length=50)),
                ("icon", models.CharField(default="git-branch", max_length=50)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="branch_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_branches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_branches",
                        to="design_branches.designbranch",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_branches",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Branch",
                "verbose_name_plural": "Design Branches",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BranchMerge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("conflicted", "Conflicted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "merge_strategy",
                    models.CharField(
                        choices=[
                            ("fast_forward", "Fast Forward"),
                            ("merge_commit", "Merge Commit"),
                            ("squash", "Squash"),
                            ("rebase", "Rebase"),
                        ],
                        default="merge_commit",
                        max_length=20,
                    ),
                ),
                ("delete_source_after_merge", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "merged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_merges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merges_as_source",
                        to="design_branches.designbranch",
                    ),
                ),
                (
                    "target_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merges_as_target",
                        to="design_branches.designbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Merge",
                "verbose_name_plural": "Branch Merges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignCommit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "commit_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("short_hash", models.CharField(editable=False, max_length=8)),
                ("design_data", models.JSONField(default=dict)),
                ("components_snapshot", models.JSONField(default=dict)),
                ("canvas_state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_auto_save", models.BooleanField(default=False)),
                ("tags", models.JSONField(default=list)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_commits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="design_branches.designbranch",
                    ),
                ),
                (
                    "co_authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="co_authored_commits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merge_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_into",
                        to="design_branches.designcommit",
                    ),
                ),
                (
                    "parent_commit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_commits",
                        to="design_branches.designcommit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Commit",
                "verbose_name_plural": "Design Commits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="designbranch",
            name="branch_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branched_from",
                to="design_branches.designcommit",
            ),
        ),
        migrations.AddField(
            model_name="designbranch",
            name="head_commit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="design_branches.designcommit",
            ),
        ),
        migrations.CreateModel(
            name="BranchReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes Requested"),
                            ("commented", "Commented"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("is_stale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "merge_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="design_branches.branchmerge",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="design_branches.designbranch",
                    ),
                ),
                (
                    "reviewed_commit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="design_branches.designcommit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Review",
                "verbose_name_plural": "Branch Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="branchmerge",
            name="merge_commit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="design_branches.designcommit",
            ),
        ),
        migrations.AddField(
            model_name="branchmerge",
            name="source_commit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="design_branches.designcommit",
            ),
        ),
        migrations.AddField(
            model_name="branchmerge",
            name="target_commit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="design_branches.designcommit",
            ),
        ),
        migrations.CreateModel(
            name="BranchComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diff_data", models.JSONField(default=dict)),
                ("additions_count", models.IntegerField(default=0)),
                ("deletions_count", models.IntegerField(default=0)),
                ("modifications_count", models.IntegerField(default=0)),
                ("is_stale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_base",
                        to="design_branches.designbranch",
                    ),
                ),
                (
                    "compare_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_compare",
                        to="design_branches.designbranch",
                    ),
                ),
                (
                    "base_commit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="design_branches.designcommit",
                    ),
                ),
                (
                    "compare_commit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="design_branches.designcommit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Comparison",
                "verbose_name_plural": "Branch Comparisons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MergeConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("property", "Property Conflict"),
                            ("position", "Position Conflict"),
                            ("deletion", "Deletion Conflict"),
                            ("creation", "Creation Conflict"),
                            ("style", "Style Conflict"),
                        ],
                        max_length=20,
                    ),
                ),
                ("element_id", models.CharField(max_length=100)),
                ("element_type", models.CharField(max_length=50)),
                ("element_name", models.CharField(blank=True, max_length=255)),
                ("property_path", models.CharField(blank=True, max_length=255)),
                ("our_value", models.JSONField(blank=True, null=True)),
                ("their_value", models.JSONField(blank=True, null=True)),
                ("base_value", models.JSONField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("none", "Unresolved"),
                            ("ours", "Keep Ours"),
                            ("theirs", "Keep Theirs"),
                            ("manual", "Manual Resolution"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("resolved_value", models.JSONField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="design_branches.branchmerge",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merge Conflict",
                "verbose_name_plural": "Merge Conflicts",
                "ordering": ["element_type", "element_name"],
            },
        ),
        migrations.CreateModel(
            name="ReviewComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                ("position_x", models.FloatField(blank=True, null=True)),
                ("position_y", models.FloatField(blank=True, null=True)),
                ("element_id", models.CharField(blank=True, max_length=100)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_review_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="design_branches.reviewcomment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_review_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="design_branches.branchreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Comment",
                "verbose_name_plural": "Review Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="designbranch",
            unique_together={("project", "name")},
        ),
        migrations.CreateModel(
            name="DesignTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("version", "Version"),
                            ("milestone", "Milestone"),
                            ("release", "Release"),
                            ("snapshot", "Snapshot"),
                        ],
                        default="version",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="#6366f1", max_length=50)),
                ("icon", models.CharField(default="tag", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_applied",
                        to="design_branches.designcommit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_design_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_tags",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Tag",
                "verbose_name_plural": "Design Tags",
                "ordering": ["-created_at"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
