# Generated by Django 5.2.10 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design_systems", "__first__"),
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        ("teams", "0003_alter_comment_mentions_alter_comment_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("total_elements", models.IntegerField(default=0)),
                ("system_elements", models.IntegerField(default=0)),
                ("adoption_rate", models.FloatField(default=0)),
                ("total_styles", models.IntegerField(default=0)),
                ("linked_styles", models.IntegerField(default=0)),
                ("style_consistency", models.FloatField(default=0)),
                ("total_components", models.IntegerField(default=0)),
                ("unmodified_components", models.IntegerField(default=0)),
                ("component_consistency", models.FloatField(default=0)),
                ("detach_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_metrics",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("widgets", models.JSONField(default=list)),
                ("default_period", models.CharField(default="30d", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "team_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeprecationNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deprecated_type",
                    models.CharField(
                        choices=[
                            ("component", "Component"),
                            ("style", "Style"),
                            ("variant", "Variant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("deprecated_id", models.CharField(max_length=100)),
                ("deprecated_name", models.CharField(max_length=255)),
                ("replacement_id", models.CharField(blank=True, max_length=100)),
                ("replacement_name", models.CharField(blank=True, max_length=255)),
                ("deprecated_at", models.DateTimeField(auto_now_add=True)),
                ("removal_date", models.DateField(blank=True, null=True)),
                ("current_usage_count", models.IntegerField(default=0)),
                ("affected_projects", models.JSONField(default=list)),
                ("migration_guide", models.TextField(blank=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deprecations",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "notified_users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-deprecated_at"],
            },
        ),
        migrations.CreateModel(
            name="ComponentUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component_id", models.CharField(max_length=100)),
                ("component_name", models.CharField(max_length=255)),
                ("component_type", models.CharField(blank=True, max_length=50)),
                ("usage_count", models.IntegerField(default=0)),
                ("project_count", models.IntegerField(default=0)),
                ("weekly_usage", models.JSONField(default=list)),
                ("monthly_usage", models.JSONField(default=list)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("override_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "last_used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_used_in_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count"],
                "unique_together": {("design_system", "component_id")},
            },
        ),
        migrations.CreateModel(
            name="DesignSystemHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessed_at", models.DateField(auto_now_add=True)),
                ("overall_score", models.FloatField(default=0)),
                ("adoption_score", models.FloatField(default=0)),
                ("consistency_score", models.FloatField(default=0)),
                ("coverage_score", models.FloatField(default=0)),
                ("freshness_score", models.FloatField(default=0)),
                ("documentation_score", models.FloatField(default=0)),
                ("issues", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_scores",
                        to="design_systems.designsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessed_at"],
                "unique_together": {("design_system", "assessed_at")},
            },
        ),
        migrations.CreateModel(
            name="StyleUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "style_type",
                    models.CharField(
                        choices=[
                            ("color", "Color"),
                            ("typography", "Typography"),
                            ("effect", "Effect"),
                            ("spacing", "Spacing"),
                            ("border_radius", "Border Radius"),
                            ("shadow", "Shadow"),
                            ("gradient", "Gradient"),
                        ],
                        max_length=20,
                    ),
                ),
                ("style_id", models.CharField(max_length=100)),
                ("style_name", models.CharField(max_length=255)),
                ("style_value", models.TextField(blank=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("project_count", models.IntegerField(default=0)),
                ("direct_usage", models.IntegerField(default=0)),
                ("hardcoded_usage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_usage_stats",
                        to="design_systems.designsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count"],
                "unique_together": {("design_system", "style_id")},
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("insert", "Component Inserted"),
                            ("update", "Component Updated"),
                            ("delete", "Component Deleted"),
                            ("detach", "Component Detached"),
                            ("swap", "Component Swapped"),
                            ("style_apply", "Style Applied"),
                            ("style_detach", "Style Detached"),
                            ("library_publish", "Library Published"),
                            ("library_update", "Library Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("component_id", models.CharField(blank=True, max_length=100)),
                ("component_name", models.CharField(blank=True, max_length=255)),
                ("style_id", models.CharField(blank=True, max_length=100)),
                ("style_name", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["design_system", "event_type", "created_at"],
                        name="design_anal_design__c25fce_idx",
                    ),
                    models.Index(
                        fields=["component_id", "created_at"],
                        name="design_anal_compone_c5c85b_idx",
                    ),
                ],
            },
        ),
    ]
