# Generated by Django 5.2.7 on 2025-11-13 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_services", "0001_initial"),
        ("projects", "0002_exporttemplate_exportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("active_users_1h", models.IntegerField(default=0)),
                ("active_users_24h", models.IntegerField(default=0)),
                ("new_users_24h", models.IntegerField(default=0)),
                ("projects_created_24h", models.IntegerField(default=0)),
                ("projects_edited_24h", models.IntegerField(default=0)),
                ("ai_requests_24h", models.IntegerField(default=0)),
                ("ai_tokens_used_24h", models.IntegerField(default=0)),
                ("ai_errors_24h", models.IntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0)),
                ("error_rate_percentage", models.FloatField(default=0)),
                ("total_storage_bytes", models.BigIntegerField(default=0)),
                ("total_assets", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="ProjectAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("edit_count", models.IntegerField(default=0)),
                ("export_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("total_edit_time_seconds", models.IntegerField(default=0)),
                ("last_viewed", models.DateTimeField(blank=True, null=True)),
                ("last_edited", models.DateTimeField(blank=True, null=True)),
                ("total_components", models.IntegerField(default=0)),
                ("ai_generated_components", models.IntegerField(default=0)),
                ("total_collaborators", models.IntegerField(default=0)),
                ("total_comments", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project analytics",
            },
        ),
        migrations.CreateModel(
            name="AIUsageMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("layout_generation", "Layout Generation"),
                            ("logo_generation", "Logo Generation"),
                            ("image_generation", "Image Generation"),
                            ("color_palette", "Color Palette"),
                            ("font_suggestion", "Font Suggestion"),
                            ("design_refinement", "Design Refinement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("model_used", models.CharField(max_length=100)),
                (
                    "request_duration_ms",
                    models.IntegerField(help_text="Duration in milliseconds"),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "generation_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_services.aigenerationrequest",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="analytics_a_user_id_c5e690_idx",
                    ),
                    models.Index(
                        fields=["service_type", "-timestamp"],
                        name="analytics_a_service_bf1f26_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyUsageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("projects_created", models.IntegerField(default=0)),
                ("projects_edited", models.IntegerField(default=0)),
                ("projects_exported", models.IntegerField(default=0)),
                ("ai_generations_count", models.IntegerField(default=0)),
                ("ai_tokens_used", models.IntegerField(default=0)),
                (
                    "ai_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("assets_uploaded", models.IntegerField(default=0)),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                ("total_edit_time_seconds", models.IntegerField(default=0)),
                ("unique_sessions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="analytics_d_user_id_e25270_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("project_create", "Project Created"),
                            ("project_update", "Project Updated"),
                            ("project_delete", "Project Deleted"),
                            ("project_export", "Project Exported"),
                            ("ai_generation", "AI Generation"),
                            ("asset_upload", "Asset Uploaded"),
                            ("template_use", "Template Used"),
                            ("collaboration_invite", "Collaboration Invite"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, help_text="Duration in milliseconds", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="analytics_u_user_id_779c80_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="analytics_u_activit_7a754e_idx",
                    ),
                ],
            },
        ),
    ]
