# Generated by Django 5.2.8 on 2025-11-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("projects", "0002_exporttemplate_exportjob"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("line_chart", "Line Chart"),
                            ("bar_chart", "Bar Chart"),
                            ("pie_chart", "Pie Chart"),
                            ("area_chart", "Area Chart"),
                            ("metric", "Single Metric"),
                            ("table", "Data Table"),
                            ("heatmap", "Heatmap"),
                            ("funnel", "Funnel"),
                            ("map", "Geographic Map"),
                            ("timeline", "Timeline"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("projects_created", "Projects Created"),
                            ("projects_completed", "Projects Completed"),
                            ("designs_exported", "Designs Exported"),
                            ("collaboration_sessions", "Collaboration Sessions"),
                            ("time_spent", "Time Spent"),
                            ("ai_generations", "AI Generations"),
                            ("template_usage", "Template Usage"),
                            ("storage_used", "Storage Used"),
                            ("team_activity", "Team Activity"),
                            ("asset_uploads", "Asset Uploads"),
                            ("comments_made", "Comments Made"),
                            ("versions_created", "Versions Created"),
                        ],
                        max_length=50,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("default_width", models.IntegerField(default=6)),
                ("default_height", models.IntegerField(default=4)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("layout", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_dashboards",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("metrics", models.JSONField(default=list)),
                ("filters", models.JSONField(default=dict)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("send_day", models.IntegerField(default=1)),
                ("send_time", models.TimeField(blank=True, null=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("recipients", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("next_send_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="analytics.analyticsdashboard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("accessibility", "Accessibility"),
                            ("performance", "Performance"),
                            ("consistency", "Consistency"),
                            ("best_practice", "Best Practice"),
                            ("trend", "Design Trend"),
                            ("improvement", "Improvement Suggestion"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("suggestion", "Suggestion"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="suggestion",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("element_id", models.CharField(blank=True, max_length=255)),
                ("element_type", models.CharField(blank=True, max_length=50)),
                ("suggestion", models.TextField(blank=True)),
                ("auto_fix_available", models.BooleanField(default=False)),
                ("auto_fix_data", models.JSONField(default=dict)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("is_applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("format", models.CharField(max_length=20)),
                ("file_size_bytes", models.BigIntegerField()),
                ("processing_time_ms", models.IntegerField()),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_analytics",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Export analytics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True)),
                ("file_size", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("data_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="analytics.analyticsreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("projects", "Projects"),
                            ("assets", "Assets"),
                            ("templates", "Templates"),
                            ("teams", "Teams"),
                            ("global", "Global"),
                        ],
                        max_length=50,
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search queries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=100)),
                (
                    "feature_category",
                    models.CharField(
                        choices=[
                            ("ai", "AI Features"),
                            ("export", "Export"),
                            ("collaboration", "Collaboration"),
                            ("design", "Design Tools"),
                            ("asset", "Asset Management"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("usage_count", models.IntegerField(default=1)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("first_used", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used"],
                "unique_together": {("user", "feature_name")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("page_load", "Page Load"),
                            ("render", "Render Performance"),
                            ("api", "API Response"),
                            ("export", "Export Performance"),
                            ("ai", "AI Processing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                ("unit", models.CharField(default="ms", max_length=20)),
                ("context", models.JSONField(default=dict)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "created_at"],
                        name="analytics_p_categor_7f5e50_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quota_type",
                    models.CharField(
                        choices=[
                            ("storage", "Storage"),
                            ("projects", "Projects"),
                            ("exports", "Exports"),
                            ("ai_generations", "AI Generations"),
                            ("collaborators", "Collaborators"),
                            ("api_calls", "API Calls"),
                        ],
                        max_length=50,
                    ),
                ),
                ("limit", models.BigIntegerField()),
                ("used", models.BigIntegerField(default=0)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("alert_threshold", models.IntegerField(default=80)),
                ("alert_sent", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_quotas",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("user", "team", "quota_type", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("project_create", "Project Created"),
                            ("project_open", "Project Opened"),
                            ("project_save", "Project Saved"),
                            ("project_export", "Project Exported"),
                            ("project_delete", "Project Deleted"),
                            ("project_share", "Project Shared"),
                            ("element_add", "Element Added"),
                            ("element_modify", "Element Modified"),
                            ("element_delete", "Element Deleted"),
                            ("layer_change", "Layer Changed"),
                            ("ai_generate", "AI Generation"),
                            ("ai_suggestion", "AI Suggestion Used"),
                            ("comment_add", "Comment Added"),
                            ("collaboration_join", "Collaboration Joined"),
                            ("collaboration_leave", "Collaboration Left"),
                            ("asset_upload", "Asset Uploaded"),
                            ("asset_use", "Asset Used"),
                            ("template_use", "Template Used"),
                            ("template_create", "Template Created"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Duration in milliseconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action_type"],
                        name="analytics_u_user_id_c9b49e_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="analytics_u_project_0727aa_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_u_created_890de2_idx"
                    ),
                ],
            },
        ),
    ]
