# Generated by Django 5.2.7 on 2025-12-03 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0002_analyticswidget_analyticsdashboard_analyticsreport_and_more",
        ),
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitorAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("competitor_url", models.URLField()),
                ("design_score", models.FloatField(blank=True, null=True)),
                ("ux_score", models.FloatField(blank=True, null=True)),
                ("accessibility_score", models.FloatField(blank=True, null=True)),
                ("colors_used", models.JSONField(default=list)),
                ("fonts_used", models.JSONField(default=list)),
                ("technologies", models.JSONField(default=list)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="competitor_screenshots/"
                    ),
                ),
                ("ai_insights", models.JSONField(default=list)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversionGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("click", "Element Click"),
                            ("page_view", "Page View"),
                            ("time_on_page", "Time on Page"),
                            ("scroll_depth", "Scroll Depth"),
                            ("form_submit", "Form Submit"),
                            ("download", "Download"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_element_id", models.CharField(blank=True, max_length=255)),
                ("target_page_id", models.CharField(blank=True, max_length=255)),
                ("target_value", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_goals",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DesignSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=255)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("screen_width", models.IntegerField(blank=True, null=True)),
                ("screen_height", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_duration", models.IntegerField(default=0)),
                ("pages_viewed", models.JSONField(default=list)),
                ("click_count", models.IntegerField(default=0)),
                ("scroll_depth", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_sessions",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("hover", "Hover"),
                            ("scroll", "Scroll"),
                            ("zoom", "Zoom"),
                            ("pan", "Pan"),
                            ("select", "Select"),
                        ],
                        max_length=20,
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("element_id", models.CharField(blank=True, max_length=255)),
                ("element_type", models.CharField(blank=True, max_length=100)),
                ("page_id", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="analytics.designsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConversionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField()),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analytics.conversiongoal",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="analytics.designsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ElementAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("element_id", models.CharField(max_length=255)),
                ("element_type", models.CharField(max_length=100)),
                ("element_name", models.CharField(blank=True, max_length=255)),
                ("click_count", models.IntegerField(default=0)),
                ("hover_count", models.IntegerField(default=0)),
                ("hover_duration_avg", models.FloatField(default=0)),
                ("visibility_count", models.IntegerField(default=0)),
                ("attention_score", models.FloatField(default=0)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_analytics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-attention_score"],
            },
        ),
        migrations.CreateModel(
            name="Heatmap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "heatmap_type",
                    models.CharField(
                        choices=[
                            ("click", "Click Heatmap"),
                            ("hover", "Hover Heatmap"),
                            ("scroll", "Scroll Heatmap"),
                            ("attention", "Attention Heatmap"),
                        ],
                        max_length=20,
                    ),
                ),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("data_points", models.JSONField(default=list)),
                ("total_interactions", models.IntegerField(default=0)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "heatmap_image",
                    models.ImageField(blank=True, null=True, upload_to="heatmaps/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heatmaps",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RealtimeAnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("widgets", models.JSONField(default=list)),
                ("default_filters", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_analytics_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RealtimeAnalyticsReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "report_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                ("metrics_included", models.JSONField(default=list)),
                ("date_range_start", models.DateTimeField()),
                ("date_range_end", models.DateTimeField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="analytics_reports/"
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_analytics_reports",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_analytics_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("steps", models.JSONField(default=list)),
                ("entry_point", models.CharField(blank=True, max_length=255)),
                ("exit_points", models.JSONField(default=list)),
                ("total_users", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0)),
                ("average_time", models.FloatField(default=0)),
                ("drop_off_points", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_flows",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("views", "Total Views"),
                            ("unique_visitors", "Unique Visitors"),
                            ("avg_time", "Average Time"),
                            ("bounce_rate", "Bounce Rate"),
                            ("engagement", "Engagement Score"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("value", models.FloatField()),
                ("previous_value", models.FloatField(blank=True, null=True)),
                ("change_percent", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_metrics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {
                    ("project", "metric_type", "period_type", "period_start")
                },
            },
        ),
    ]
