# Generated by Django 5.2.10 on 2026-01-28 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAppVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")], max_length=20
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("build_number", models.IntegerField()),
                ("is_required", models.BooleanField(default=False)),
                ("is_latest", models.BooleanField(default=False)),
                ("is_deprecated", models.BooleanField(default=False)),
                ("store_url", models.URLField(blank=True)),
                ("release_notes", models.TextField(blank=True)),
                ("min_api_version", models.CharField(blank=True, max_length=50)),
                ("released_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mobile App Version",
                "verbose_name_plural": "Mobile App Versions",
                "ordering": ["-build_number"],
                "unique_together": {("platform", "version")},
            },
        ),
        migrations.CreateModel(
            name="MobileDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_id", models.CharField(max_length=255, unique=True)),
                ("device_name", models.CharField(blank=True, max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")], max_length=20
                    ),
                ),
                ("os_version", models.CharField(blank=True, max_length=50)),
                ("app_version", models.CharField(blank=True, max_length=50)),
                ("push_token", models.CharField(blank=True, max_length=500)),
                ("push_enabled", models.BooleanField(default=True)),
                ("supports_biometrics", models.BooleanField(default=False)),
                ("biometrics_enabled", models.BooleanField(default=False)),
                ("screen_width", models.IntegerField(blank=True, null=True)),
                ("screen_height", models.IntegerField(blank=True, null=True)),
                ("screen_scale", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("trusted", models.BooleanField(default=False)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Device",
                "verbose_name_plural": "Mobile Devices",
                "ordering": ["-last_active"],
            },
        ),
        migrations.CreateModel(
            name="MobileAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("pin", "Pin/Comment"),
                            ("draw", "Drawing"),
                            ("voice", "Voice Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("screen_id", models.CharField(blank=True, max_length=100)),
                ("comment", models.TextField(blank=True)),
                ("drawing_data", models.JSONField(blank=True, null=True)),
                (
                    "voice_recording",
                    models.FileField(
                        blank=True, null=True, upload_to="voice_annotations/"
                    ),
                ),
                ("voice_duration", models.IntegerField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("synced", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_annotations",
                        to="projects.project",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_mobile_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotations",
                        to="mobile_api.mobiledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Annotation",
                "verbose_name_plural": "Mobile Annotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MobileNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("mention", "Mention"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("update", "Update"),
                            ("review", "Review Request"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("project_id", models.CharField(blank=True, max_length=100)),
                ("comment_id", models.CharField(blank=True, max_length=100)),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("push_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="mobile_api.mobiledevice",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_mobile_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Notification",
                "verbose_name_plural": "Mobile Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MobilePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("default_zoom", models.FloatField(default=1.0)),
                ("dark_mode", models.BooleanField(default=False)),
                ("reduced_motion", models.BooleanField(default=False)),
                ("notify_comments", models.BooleanField(default=True)),
                ("notify_mentions", models.BooleanField(default=True)),
                ("notify_updates", models.BooleanField(default=True)),
                ("notify_reviews", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("auto_download_projects", models.BooleanField(default=False)),
                ("max_cache_size", models.BigIntegerField(default=524288000)),
                ("wifi_only", models.BooleanField(default=True)),
                ("require_auth_for_view", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Preference",
                "verbose_name_plural": "Mobile Preferences",
            },
        ),
        migrations.CreateModel(
            name="MobileSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_token", models.CharField(max_length=255, unique=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("current_project_id", models.CharField(blank=True, max_length=100)),
                ("current_view", models.CharField(blank=True, max_length=50)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mobile_api.mobiledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Session",
                "verbose_name_plural": "Mobile Sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="OfflineCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("component", "Component"),
                            ("asset", "Asset"),
                            ("presentation", "Presentation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.CharField(max_length=100)),
                ("version", models.IntegerField(default=1)),
                ("server_updated_at", models.DateTimeField()),
                ("cached_at", models.DateTimeField(auto_now=True)),
                ("is_stale", models.BooleanField(default=False)),
                ("cache_size", models.BigIntegerField(default=0)),
                ("priority", models.IntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_cache",
                        to="mobile_api.mobiledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Cache",
                "verbose_name_plural": "Offline Caches",
                "ordering": ["-priority", "-cached_at"],
                "unique_together": {("device", "cache_type", "content_id")},
            },
        ),
    ]
