# Generated by Django 5.2.10 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV File"),
                            ("json", "JSON File"),
                            ("rest_api", "REST API"),
                            ("graphql", "GraphQL API"),
                            ("database", "Database"),
                            ("google_sheets", "Google Sheets"),
                            ("airtable", "Airtable"),
                            ("firebase", "Firebase"),
                            ("supabase", "Supabase"),
                            ("notion", "Notion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="data_sources/"),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "No Authentication"),
                            ("api_key", "API Key"),
                            ("bearer", "Bearer Token"),
                            ("basic", "Basic Auth"),
                            ("oauth2", "OAuth 2.0"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("auth_config", models.JSONField(blank=True, default=dict)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("body_template", models.TextField(blank=True)),
                (
                    "data_path",
                    models.CharField(
                        blank=True, help_text="JSONPath to data array", max_length=255
                    ),
                ),
                ("schema", models.JSONField(blank=True, default=dict)),
                (
                    "cache_duration",
                    models.IntegerField(
                        default=300, help_text="Cache duration in seconds"
                    ),
                ),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
                ("cached_data", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("filter_expression", models.TextField(blank=True)),
                ("sort_field", models.CharField(blank=True, max_length=100)),
                (
                    "sort_direction",
                    models.CharField(
                        choices=[("asc", "Ascending"), ("desc", "Descending")],
                        default="asc",
                        max_length=4,
                    ),
                ),
                ("page_size", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_collections",
                        to="projects.project",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="data_binding.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("records_fetched", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="data_binding.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataTransform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "transform_type",
                    models.CharField(
                        choices=[
                            ("format_date", "Format Date"),
                            ("format_number", "Format Number"),
                            ("format_currency", "Format Currency"),
                            ("truncate", "Truncate Text"),
                            ("uppercase", "Uppercase"),
                            ("lowercase", "Lowercase"),
                            ("capitalize", "Capitalize"),
                            ("replace", "Find & Replace"),
                            ("custom", "Custom JavaScript"),
                        ],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_transforms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataVariable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "variable_type",
                    models.CharField(
                        choices=[
                            ("string", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                            ("image", "Image URL"),
                            ("url", "URL"),
                            ("color", "Color"),
                            ("json", "JSON Object"),
                            ("array", "Array"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "field_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to field in data source",
                        max_length=255,
                    ),
                ),
                ("default_value", models.TextField(blank=True)),
                (
                    "transform",
                    models.TextField(
                        blank=True, help_text="JavaScript transform function"
                    ),
                ),
                ("format_string", models.CharField(blank=True, max_length=255)),
                ("current_value", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="data_binding.datasource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_variables",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="DataBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("element_id", models.CharField(max_length=100)),
                ("element_name", models.CharField(blank=True, max_length=255)),
                (
                    "binding_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Content"),
                            ("src", "Image Source"),
                            ("href", "Link URL"),
                            ("fill", "Fill Color"),
                            ("stroke", "Stroke Color"),
                            ("opacity", "Opacity"),
                            ("visibility", "Visibility"),
                            ("width", "Width"),
                            ("height", "Height"),
                            ("style", "CSS Style"),
                            ("class", "CSS Class"),
                            ("data", "Data Attribute"),
                        ],
                        max_length=20,
                    ),
                ),
                ("property_name", models.CharField(blank=True, max_length=100)),
                (
                    "condition",
                    models.TextField(blank=True, help_text="JavaScript condition"),
                ),
                ("true_value", models.TextField(blank=True)),
                ("false_value", models.TextField(blank=True)),
                (
                    "template",
                    models.TextField(
                        blank=True, help_text="Template with {{variable}} placeholders"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_bindings",
                        to="projects.project",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bindings",
                        to="data_binding.datavariable",
                    ),
                ),
            ],
            options={
                "ordering": ["element_id", "binding_type"],
            },
        ),
        migrations.CreateModel(
            name="RepeatingElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("element_id", models.CharField(max_length=100)),
                (
                    "template_element",
                    models.TextField(help_text="JSON template of the element"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                            ("grid", "Grid"),
                        ],
                        default="vertical",
                        max_length=10,
                    ),
                ),
                ("gap", models.FloatField(default=10)),
                ("columns", models.IntegerField(default=1)),
                ("alternate_styles", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeating_elements",
                        to="data_binding.datacollection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeating_elements",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
