# Generated by Django 5.2.10 on 2026-01-28 12:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimationComposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("width", models.IntegerField(default=1920)),
                ("height", models.IntegerField(default=1080)),
                ("frame_rate", models.FloatField(blank=True, null=True)),
                ("duration", models.FloatField(default=3.0)),
                ("work_area_start", models.FloatField(default=0)),
                ("work_area_end", models.FloatField(blank=True, null=True)),
                (
                    "background_color",
                    models.CharField(default="transparent", max_length=50),
                ),
                ("background_opacity", models.FloatField(default=1.0)),
                ("is_main", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="compositions/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Animation Composition",
                "verbose_name_plural": "Animation Compositions",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AnimationLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("shape", "Shape"),
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("null", "Null Object"),
                            ("camera", "Camera"),
                            ("composition", "Composition"),
                            ("solid", "Solid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_data", models.JSONField(default=dict)),
                ("in_point", models.FloatField(default=0)),
                ("out_point", models.FloatField(blank=True, null=True)),
                ("start_offset", models.FloatField(default=0)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("position_z", models.FloatField(default=0)),
                ("anchor_x", models.FloatField(default=0)),
                ("anchor_y", models.FloatField(default=0)),
                ("scale_x", models.FloatField(default=100)),
                ("scale_y", models.FloatField(default=100)),
                ("scale_z", models.FloatField(default=100)),
                ("rotation", models.FloatField(default=0)),
                ("rotation_x", models.FloatField(default=0)),
                ("rotation_y", models.FloatField(default=0)),
                ("opacity", models.FloatField(default=100)),
                ("order", models.IntegerField(default=0)),
                ("visible", models.BooleanField(default=True)),
                ("locked", models.BooleanField(default=False)),
                ("solo", models.BooleanField(default=False)),
                ("shy", models.BooleanField(default=False)),
                ("is_3d", models.BooleanField(default=False)),
                ("collapse_transform", models.BooleanField(default=False)),
                ("motion_blur", models.BooleanField(default=False)),
                ("motion_blur_samples", models.IntegerField(default=16)),
                (
                    "blend_mode",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("multiply", "Multiply"),
                            ("screen", "Screen"),
                            ("overlay", "Overlay"),
                            ("darken", "Darken"),
                            ("lighten", "Lighten"),
                            ("color-dodge", "Color Dodge"),
                            ("color-burn", "Color Burn"),
                            ("hard-light", "Hard Light"),
                            ("soft-light", "Soft Light"),
                            ("difference", "Difference"),
                            ("exclusion", "Exclusion"),
                            ("hue", "Hue"),
                            ("saturation", "Saturation"),
                            ("color", "Color"),
                            ("luminosity", "Luminosity"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "track_matte_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("alpha", "Alpha Matte"),
                            ("alpha_inverted", "Alpha Inverted"),
                            ("luma", "Luma Matte"),
                            ("luma_inverted", "Luma Inverted"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("color_label", models.CharField(default="#808080", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "composition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="animation_timeline.animationcomposition",
                    ),
                ),
                (
                    "design_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animation_layers",
                        to="projects.designcomponent",
                    ),
                ),
                (
                    "nested_composition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_in_layers",
                        to="animation_timeline.animationcomposition",
                    ),
                ),
                (
                    "parent_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_layers",
                        to="animation_timeline.animationlayer",
                    ),
                ),
                (
                    "track_matte_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matte_for_layers",
                        to="animation_timeline.animationlayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animation Layer",
                "verbose_name_plural": "Animation Layers",
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="AnimationEffect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("blur", "Blur"),
                            ("gaussian_blur", "Gaussian Blur"),
                            ("motion_blur", "Motion Blur"),
                            ("drop_shadow", "Drop Shadow"),
                            ("inner_shadow", "Inner Shadow"),
                            ("glow", "Glow"),
                            ("color_correction", "Color Correction"),
                            ("hue_saturation", "Hue/Saturation"),
                            ("brightness_contrast", "Brightness/Contrast"),
                            ("levels", "Levels"),
                            ("curves", "Curves"),
                            ("gradient_overlay", "Gradient Overlay"),
                            ("pattern_overlay", "Pattern Overlay"),
                            ("stroke", "Stroke"),
                            ("displacement", "Displacement"),
                            ("turbulent_displace", "Turbulent Displace"),
                            ("wave_warp", "Wave Warp"),
                            ("spherize", "Spherize"),
                            ("twirl", "Twirl"),
                            ("vignette", "Vignette"),
                            ("noise", "Noise"),
                            ("grain", "Grain"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("parameters", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("expanded", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="animation_timeline.animationlayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animation Effect",
                "verbose_name_plural": "Animation Effects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AnimationProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "frame_rate",
                    models.FloatField(
                        default=60.0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                ("default_duration", models.FloatField(default=3.0)),
                ("width", models.IntegerField(default=1920)),
                ("height", models.IntegerField(default=1080)),
                (
                    "background_color",
                    models.CharField(default="#ffffff", max_length=50),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="animation_projects/"
                    ),
                ),
                ("preview_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("is_template", models.BooleanField(default=False)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animation_projects",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animation_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Animation Project",
                "verbose_name_plural": "Animation Projects",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="animationcomposition",
            name="animation_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compositions",
                to="animation_timeline.animationproject",
            ),
        ),
        migrations.CreateModel(
            name="AnimationSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("click", "On Click"),
                            ("hover", "On Hover"),
                            ("hover_end", "On Hover End"),
                            ("load", "On Load"),
                            ("scroll", "On Scroll"),
                            ("drag", "On Drag"),
                            ("key_press", "On Key Press"),
                            ("timer", "After Timer"),
                            ("custom", "Custom Trigger"),
                        ],
                        default="click",
                        max_length=20,
                    ),
                ),
                ("trigger_config", models.JSONField(default=dict)),
                ("duration", models.FloatField(default=0.3)),
                ("delay", models.FloatField(default=0)),
                ("animations", models.JSONField(default=list)),
                ("loop", models.BooleanField(default=False)),
                ("loop_count", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animation_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="animation_timeline.animationproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animation Sequence",
                "verbose_name_plural": "Animation Sequences",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AnimationTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("position_x", "Position X"),
                            ("position_y", "Position Y"),
                            ("position_z", "Position Z"),
                            ("anchor_x", "Anchor X"),
                            ("anchor_y", "Anchor Y"),
                            ("scale_x", "Scale X"),
                            ("scale_y", "Scale Y"),
                            ("scale_z", "Scale Z"),
                            ("scale_uniform", "Scale Uniform"),
                            ("rotation", "Rotation"),
                            ("rotation_x", "Rotation X"),
                            ("rotation_y", "Rotation Y"),
                            ("rotation_z", "Rotation Z"),
                            ("opacity", "Opacity"),
                            ("fill_color", "Fill Color"),
                            ("stroke_color", "Stroke Color"),
                            ("stroke_width", "Stroke Width"),
                            ("path", "Path"),
                            ("corner_radius", "Corner Radius"),
                            ("text_content", "Text Content"),
                            ("font_size", "Font Size"),
                            ("letter_spacing", "Letter Spacing"),
                            ("line_height", "Line Height"),
                            ("blur", "Blur"),
                            ("brightness", "Brightness"),
                            ("contrast", "Contrast"),
                            ("saturate", "Saturate"),
                            ("custom", "Custom Property"),
                        ],
                        max_length=30,
                    ),
                ),
                ("property_path", models.CharField(blank=True, max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("expanded", models.BooleanField(default=True)),
                ("expression", models.TextField(blank=True)),
                ("expression_enabled", models.BooleanField(default=False)),
                ("color", models.CharField(default="#6366f1", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="animation_timeline.animationlayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animation Track",
                "verbose_name_plural": "Animation Tracks",
                "ordering": ["property_type"],
            },
        ),
        migrations.CreateModel(
            name="AnimationKeyframe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "time",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("value", models.JSONField()),
                (
                    "interpolation",
                    models.CharField(
                        choices=[
                            ("linear", "Linear"),
                            ("bezier", "Bezier"),
                            ("hold", "Hold"),
                            ("ease", "Ease"),
                            ("ease_in", "Ease In"),
                            ("ease_out", "Ease Out"),
                            ("ease_in_out", "Ease In Out"),
                            ("spring", "Spring"),
                            ("bounce", "Bounce"),
                            ("elastic", "Elastic"),
                        ],
                        default="ease_in_out",
                        max_length=20,
                    ),
                ),
                ("handle_in_x", models.FloatField(default=0)),
                ("handle_in_y", models.FloatField(default=0)),
                ("handle_out_x", models.FloatField(default=0)),
                ("handle_out_y", models.FloatField(default=0)),
                ("temporal_ease_in", models.FloatField(default=0.33)),
                ("temporal_ease_out", models.FloatField(default=0.33)),
                ("spatial_tangent_in", models.JSONField(blank=True, null=True)),
                ("spatial_tangent_out", models.JSONField(blank=True, null=True)),
                ("roving", models.BooleanField(default=False)),
                ("spring_stiffness", models.FloatField(default=100)),
                ("spring_damping", models.FloatField(default=10)),
                ("spring_mass", models.FloatField(default=1)),
                ("is_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyframes",
                        to="animation_timeline.animationtrack",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animation Keyframe",
                "verbose_name_plural": "Animation Keyframes",
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="EasingPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ease", "Ease"),
                            ("bounce", "Bounce"),
                            ("elastic", "Elastic"),
                            ("spring", "Spring"),
                            ("steps", "Steps"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("x1", models.FloatField(default=0.42)),
                ("y1", models.FloatField(default=0)),
                ("x2", models.FloatField(default=0.58)),
                ("y2", models.FloatField(default=1)),
                ("spring_config", models.JSONField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="easing_presets/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="easing_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Easing Preset",
                "verbose_name_plural": "Easing Presets",
                "ordering": ["-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="LottieExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("low", "Low (smaller file)"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("lossless", "Lossless (largest file)"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("include_hidden_layers", models.BooleanField(default=False)),
                ("lottie_file", models.FileField(upload_to="lottie_exports/")),
                ("file_size", models.BigIntegerField(default=0)),
                ("lottie_version", models.CharField(default="5.9.0", max_length=50)),
                ("lottie_data", models.JSONField(blank=True, null=True)),
                (
                    "preview_gif",
                    models.FileField(
                        blank=True, null=True, upload_to="lottie_previews/"
                    ),
                ),
                (
                    "preview_mp4",
                    models.FileField(
                        blank=True, null=True, upload_to="lottie_previews/"
                    ),
                ),
                ("duration", models.FloatField(blank=True, null=True)),
                ("frame_count", models.IntegerField(blank=True, null=True)),
                ("layer_count", models.IntegerField(blank=True, null=True)),
                ("supported_features", models.JSONField(default=list)),
                ("unsupported_features", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "composition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lottie_exports",
                        to="animation_timeline.animationcomposition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lottie_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lottie Export",
                "verbose_name_plural": "Lottie Exports",
                "ordering": ["-created_at"],
            },
        ),
    ]
