# Generated by Django 5.2.10 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityGuideline",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("principle", models.CharField(max_length=100)),
                ("guideline", models.CharField(max_length=255)),
                ("criterion", models.CharField(max_length=255)),
                ("level", models.CharField(max_length=3)),
                ("description", models.TextField()),
                ("understanding_url", models.URLField(blank=True)),
                ("how_to_meet_url", models.URLField(blank=True)),
                ("sufficient_techniques", models.JSONField(default=list)),
                ("advisory_techniques", models.JSONField(default=list)),
                ("failures", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        choices=[
                            ("A", "Level A"),
                            ("AA", "Level AA"),
                            ("AAA", "Level AAA"),
                        ],
                        default="AA",
                        max_length=3,
                    ),
                ),
                ("test_categories", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0)),
                ("passed", models.BooleanField(blank=True, null=True)),
                ("total_issues", models.IntegerField(default=0)),
                ("errors", models.IntegerField(default=0)),
                ("warnings", models.IntegerField(default=0)),
                ("notices", models.IntegerField(default=0)),
                ("results", models.JSONField(default=dict)),
                ("accessibility_score", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_tests",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("html", "HTML Report"),
                            ("pdf", "PDF Report"),
                            ("json", "JSON Data"),
                            ("csv", "CSV Export"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="accessibility_reports/"
                    ),
                ),
                ("include_summary", models.BooleanField(default=True)),
                ("include_issues", models.BooleanField(default=True)),
                ("include_screenshots", models.BooleanField(default=True)),
                ("include_recommendations", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="accessibility_testing.accessibilitytest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("notice", "Notice"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("contrast", "Color Contrast"),
                            ("focus", "Focus Order"),
                            ("keyboard", "Keyboard Navigation"),
                            ("screen_reader", "Screen Reader"),
                            ("alt_text", "Alternative Text"),
                            ("semantics", "Semantic Structure"),
                            ("motion", "Motion & Animation"),
                            ("color_alone", "Color as Only Indicator"),
                            ("text_size", "Text Size"),
                            ("touch_target", "Touch Target Size"),
                            ("timing", "Timing"),
                            ("language", "Language"),
                        ],
                        max_length=20,
                    ),
                ),
                ("wcag_criterion", models.CharField(max_length=20)),
                ("wcag_level", models.CharField(max_length=3)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("how_to_fix", models.TextField(blank=True)),
                ("element_id", models.CharField(blank=True, max_length=100)),
                ("element_type", models.CharField(blank=True, max_length=50)),
                ("element_name", models.CharField(blank=True, max_length=255)),
                ("current_value", models.JSONField(default=dict)),
                ("suggested_fix", models.JSONField(default=dict)),
                ("auto_fixable", models.BooleanField(default=False)),
                ("is_fixed", models.BooleanField(default=False)),
                ("ignored", models.BooleanField(default=False)),
                ("ignore_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="accessibility_testing.accessibilitytest",
                    ),
                ),
            ],
            options={
                "ordering": ["severity", "category"],
            },
        ),
        migrations.CreateModel(
            name="ColorBlindnessSimulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "simulation_type",
                    models.CharField(
                        choices=[
                            ("protanopia", "Protanopia (No Red)"),
                            ("deuteranopia", "Deuteranopia (No Green)"),
                            ("tritanopia", "Tritanopia (No Blue)"),
                            ("protanomaly", "Protanomaly (Weak Red)"),
                            ("deuteranomaly", "Deuteranomaly (Weak Green)"),
                            ("tritanomaly", "Tritanomaly (Weak Blue)"),
                            ("achromatopsia", "Achromatopsia (Monochrome)"),
                            ("achromatomaly", "Achromatomaly (Weak Color)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("frame_id", models.CharField(blank=True, max_length=100)),
                (
                    "original_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="accessibility/original/"
                    ),
                ),
                (
                    "simulated_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="accessibility/simulated/"
                    ),
                ),
                ("color_mapping", models.JSONField(default=dict)),
                ("issues", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_blindness_simulations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContrastCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("element_id", models.CharField(max_length=100)),
                ("element_type", models.CharField(max_length=50)),
                ("element_name", models.CharField(blank=True, max_length=255)),
                ("foreground_color", models.CharField(max_length=20)),
                ("background_color", models.CharField(max_length=20)),
                ("contrast_ratio", models.FloatField()),
                ("font_size", models.FloatField(blank=True, null=True)),
                ("is_large_text", models.BooleanField(default=False)),
                ("is_bold", models.BooleanField(default=False)),
                ("passes_aa", models.BooleanField(default=False)),
                ("passes_aaa", models.BooleanField(default=False)),
                ("suggested_foreground", models.CharField(blank=True, max_length=20)),
                ("suggested_background", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrast_checks",
                        to="projects.project",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrast_checks",
                        to="accessibility_testing.accessibilitytest",
                    ),
                ),
            ],
            options={
                "ordering": ["contrast_ratio"],
            },
        ),
        migrations.CreateModel(
            name="FocusOrderTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("frame_id", models.CharField(blank=True, max_length=100)),
                ("focus_order", models.JSONField(default=list)),
                ("issues", models.JSONField(default=list)),
                ("focus_indicator_issues", models.JSONField(default=list)),
                ("visualization_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_order_tests",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScreenReaderPreview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("frame_id", models.CharField(blank=True, max_length=100)),
                ("content", models.JSONField(default=list)),
                ("speech_text", models.TextField(blank=True)),
                ("reading_order_issues", models.JSONField(default=list)),
                ("missing_alt_text", models.JSONField(default=list)),
                ("aria_analysis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_reader_previews",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
