# Generated by Django 5.2.8 on 2025-11-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0001_initial"),
        ("projects", "0002_exporttemplate_exportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("color", "Color Trends"),
                            ("typography", "Typography Trends"),
                            ("layout", "Layout Trends"),
                            ("style", "Style Trends"),
                            ("component", "Component Trends"),
                            ("animation", "Animation Trends"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("trend_data", models.JSONField(default=dict)),
                ("popularity_score", models.FloatField(default=0)),
                (
                    "growth_rate",
                    models.FloatField(default=0, help_text="Percentage growth"),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("industries", models.JSONField(default=list)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-popularity_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIDesignSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("color", "Color Improvement"),
                            ("typography", "Typography Improvement"),
                            ("layout", "Layout Improvement"),
                            ("accessibility", "Accessibility"),
                            ("performance", "Performance"),
                            ("consistency", "Consistency"),
                            ("trend", "Trend Alignment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("affected_element_ids", models.JSONField(default=list)),
                ("suggested_changes", models.JSONField(default=dict)),
                ("is_applied", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("user_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="New Conversation", max_length=255)),
                (
                    "context_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Project or design context"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "AI Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Attachments, references, etc.",
                    ),
                ),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_services.chatconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="ai_services.aigenerationrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="ai_services.chatmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageToDesignRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_image",
                    models.ImageField(upload_to="ai/image_to_design/%Y/%m/"),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True, help_text="Additional instructions for conversion"
                    ),
                ),
                (
                    "target_design_type",
                    models.CharField(default="ui_ux", max_length=50),
                ),
                ("extract_colors", models.BooleanField(default=True)),
                ("extract_typography", models.BooleanField(default=True)),
                ("extract_layout", models.BooleanField(default=True)),
                ("preserve_style", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_to_design_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StyleTransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style_preset",
                    models.CharField(
                        choices=[
                            ("apple", "Apple Design"),
                            ("google_material", "Google Material"),
                            ("microsoft_fluent", "Microsoft Fluent"),
                            ("minimalist", "Minimalist"),
                            ("brutalist", "Brutalist"),
                            ("scandinavian", "Scandinavian"),
                            ("retro", "Retro"),
                            ("futuristic", "Futuristic"),
                            ("organic", "Organic"),
                            ("corporate", "Corporate"),
                            ("playful", "Playful"),
                            ("elegant", "Elegant"),
                            ("custom", "Custom"),
                        ],
                        default="minimalist",
                        max_length=50,
                    ),
                ),
                (
                    "style_reference_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ai/style_reference/%Y/%m/"
                    ),
                ),
                ("style_description", models.TextField(blank=True)),
                ("transfer_colors", models.BooleanField(default=True)),
                ("transfer_typography", models.BooleanField(default=True)),
                ("transfer_spacing", models.BooleanField(default=True)),
                ("transfer_shapes", models.BooleanField(default=True)),
                (
                    "intensity",
                    models.FloatField(
                        default=0.8, help_text="Style transfer intensity (0-1)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="style_transfer_results",
                        to="projects.project",
                    ),
                ),
                (
                    "source_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_transfers",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_transfer_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrendAnalysisRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        blank=True, help_text="0-100 trend alignment score", null=True
                    ),
                ),
                ("color_score", models.FloatField(blank=True, null=True)),
                ("typography_score", models.FloatField(blank=True, null=True)),
                ("layout_score", models.FloatField(blank=True, null=True)),
                ("recommendations", models.JSONField(default=list)),
                ("analysis_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_trends",
                    models.ManyToManyField(blank=True, to="ai_services.designtrend"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend_analyses",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceToDesignRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="ai/voice_to_design/%Y/%m/")),
                ("audio_duration_seconds", models.FloatField(blank=True, null=True)),
                ("transcribed_text", models.TextField(blank=True)),
                ("transcription_confidence", models.FloatField(blank=True, null=True)),
                ("design_type", models.CharField(default="ui_ux", max_length=50)),
                ("additional_context", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("transcribing", "Transcribing"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("transcription_model", models.CharField(blank=True, max_length=100)),
                ("generation_model", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_to_design_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
