# Generated by Django 5.2.10 on 2026-01-28 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        ("teams", "0004_alter_task_assigned_to_alter_task_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("components", models.JSONField(default=list)),
                ("default_framework", models.CharField(default="react", max_length=30)),
                (
                    "default_styling",
                    models.CharField(default="tailwind", max_length=30),
                ),
                ("package_name", models.CharField(blank=True, max_length=255)),
                ("package_registry", models.CharField(default="npm", max_length=50)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_libraries",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_libraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Component libraries",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("dimensions", models.JSONField(default=dict)),
                ("colors", models.JSONField(default=dict)),
                ("typography", models.JSONField(default=dict)),
                ("spacing", models.JSONField(default=dict)),
                ("effects", models.JSONField(default=dict)),
                ("computed_styles", models.JSONField(default=dict)),
                ("assets", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("implementation_hints", models.JSONField(default=list)),
                ("auto_generated", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="projects.designcomponent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_specs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("react", "React"),
                            ("vue", "Vue.js"),
                            ("angular", "Angular"),
                            ("svelte", "Svelte"),
                            ("html", "HTML/CSS"),
                            ("swiftui", "SwiftUI (iOS)"),
                            ("jetpack_compose", "Jetpack Compose (Android)"),
                            ("flutter", "Flutter"),
                            ("react_native", "React Native"),
                        ],
                        default="react",
                        max_length=30,
                    ),
                ),
                (
                    "styling",
                    models.CharField(
                        choices=[
                            ("tailwind", "Tailwind CSS"),
                            ("css_modules", "CSS Modules"),
                            ("styled_components", "Styled Components"),
                            ("emotion", "Emotion"),
                            ("scss", "SCSS"),
                            ("vanilla_css", "Vanilla CSS"),
                            ("chakra_ui", "Chakra UI"),
                            ("material_ui", "Material UI"),
                        ],
                        default="tailwind",
                        max_length=30,
                    ),
                ),
                ("typescript_enabled", models.BooleanField(default=True)),
                (
                    "component_naming",
                    models.CharField(default="PascalCase", max_length=20),
                ),
                ("use_absolute_imports", models.BooleanField(default=True)),
                ("generate_tests", models.BooleanField(default=False)),
                ("generate_storybook", models.BooleanField(default=False)),
                ("breakpoints", models.JSONField(default=dict)),
                ("generate_responsive", models.BooleanField(default=True)),
                ("custom_config", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("framework", models.CharField(max_length=30)),
                ("styling", models.CharField(max_length=30)),
                ("generated_code", models.JSONField(default=dict)),
                ("preview_url", models.URLField(blank=True)),
                ("download_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("file_count", models.IntegerField(default=0)),
                ("total_lines", models.IntegerField(default=0)),
                ("export_size", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_export_records",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_export_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="code_export.exportconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HandoffAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("dimension", "Dimension"),
                            ("spacing", "Spacing"),
                            ("color", "Color"),
                            ("typography", "Typography"),
                            ("interaction", "Interaction"),
                            ("note", "Note"),
                            ("asset", "Asset"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("color", models.CharField(default="#3B82F6", max_length=20)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.designcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff_annotations",
                        to="projects.project",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
