# Generated by Django 5.2.10 on 2026-01-29 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_export", "0001_initial"),
        ("projects", "0007_alter_batchoperation_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="handoffannotation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_export_handoff_annotations",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="handoffannotation",
            name="resolved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="code_export_resolved_annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
