# Generated by Django 5.2.10 on 2026-01-29 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commenting", "0001_initial"),
        ("projects", "0007_alter_batchoperation_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewsession",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commenting_review_sessions",
                to="projects.project",
            ),
        ),
    ]
