# Generated by Django 5.2.10 on 2026-01-28 17:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpositionLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "imposition_type",
                    models.CharField(
                        choices=[
                            ("saddle_stitch", "Saddle Stitch"),
                            ("perfect_bind", "Perfect Binding"),
                            ("gang_up", "Gang-Up / N-Up"),
                            ("step_repeat", "Step & Repeat"),
                            ("booklet", "Booklet"),
                            ("folding", "Folding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("sheet_width", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sheet_height", models.DecimalField(decimal_places=2, max_digits=8)),
                ("columns", models.IntegerField(default=2)),
                ("rows", models.IntegerField(default=2)),
                (
                    "margin_top",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=6
                    ),
                ),
                (
                    "margin_bottom",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=6
                    ),
                ),
                (
                    "margin_left",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=6
                    ),
                ),
                (
                    "margin_right",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=6
                    ),
                ),
                (
                    "horizontal_gap",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "vertical_gap",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("page_ordering", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrintProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital Printing"),
                            ("offset", "Offset Printing"),
                            ("large_format", "Large Format"),
                            ("newspaper", "Newspaper"),
                            ("magazine", "Magazine"),
                            ("packaging", "Packaging"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("recommended_dpi", models.IntegerField(default=300)),
                (
                    "recommended_color_mode",
                    models.CharField(default="cmyk", max_length=20),
                ),
                (
                    "recommended_bleed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=6
                    ),
                ),
                ("pdf_standard", models.CharField(default="pdf_x_4", max_length=20)),
                ("icc_profile", models.CharField(blank=True, max_length=100)),
                ("icc_profile_url", models.URLField(blank=True)),
                ("settings", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PDFExportPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "paper_size",
                    models.CharField(
                        choices=[
                            ("letter", "Letter (8.5 x 11 in)"),
                            ("legal", "Legal (8.5 x 14 in)"),
                            ("tabloid", "Tabloid (11 x 17 in)"),
                            ("a3", "A3 (297 x 420 mm)"),
                            ("a4", "A4 (210 x 297 mm)"),
                            ("a5", "A5 (148 x 210 mm)"),
                            ("custom", "Custom Size"),
                        ],
                        default="letter",
                        max_length=20,
                    ),
                ),
                (
                    "custom_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "custom_height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("orientation", models.CharField(default="portrait", max_length=20)),
                (
                    "color_mode",
                    models.CharField(
                        choices=[
                            ("rgb", "RGB (Screen)"),
                            ("cmyk", "CMYK (Print)"),
                            ("grayscale", "Grayscale"),
                        ],
                        default="rgb",
                        max_length=20,
                    ),
                ),
                ("icc_profile", models.CharField(blank=True, max_length=100)),
                ("bleed_enabled", models.BooleanField(default=False)),
                (
                    "bleed_top",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=6
                    ),
                ),
                (
                    "bleed_bottom",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=6
                    ),
                ),
                (
                    "bleed_left",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=6
                    ),
                ),
                (
                    "bleed_right",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=6
                    ),
                ),
                ("crop_marks", models.BooleanField(default=False)),
                ("bleed_marks", models.BooleanField(default=False)),
                ("registration_marks", models.BooleanField(default=False)),
                ("color_bars", models.BooleanField(default=False)),
                ("page_info", models.BooleanField(default=False)),
                (
                    "mark_offset",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=6
                    ),
                ),
                (
                    "mark_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.25"), max_digits=4
                    ),
                ),
                (
                    "pdf_standard",
                    models.CharField(
                        choices=[
                            ("pdf_1_7", "PDF 1.7"),
                            ("pdf_2_0", "PDF 2.0"),
                            ("pdf_a_1b", "PDF/A-1b (Archival)"),
                            ("pdf_a_2b", "PDF/A-2b (Archival)"),
                            ("pdf_x_1a", "PDF/X-1a (Print)"),
                            ("pdf_x_3", "PDF/X-3 (Print)"),
                            ("pdf_x_4", "PDF/X-4 (Print)"),
                        ],
                        default="pdf_1_7",
                        max_length=20,
                    ),
                ),
                (
                    "quality",
                    models.IntegerField(
                        default=300,
                        validators=[
                            django.core.validators.MinValueValidator(72),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                ("compress_images", models.BooleanField(default=True)),
                (
                    "image_quality",
                    models.IntegerField(
                        default=85,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("embed_fonts", models.BooleanField(default=True)),
                ("subset_fonts", models.BooleanField(default=True)),
                ("password_protect", models.BooleanField(default=False)),
                ("allow_printing", models.BooleanField(default=True)),
                ("allow_copying", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PDFExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages", models.JSONField(default=list)),
                ("page_range", models.CharField(blank=True, max_length=100)),
                ("export_settings", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("page_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_export_jobs",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pdf_export.pdfexportpreset",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Export",
                "verbose_name_plural": "PDF Exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("header_enabled", models.BooleanField(default=False)),
                ("header_content", models.JSONField(default=dict)),
                (
                    "header_height",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=6
                    ),
                ),
                ("footer_enabled", models.BooleanField(default=False)),
                ("footer_content", models.JSONField(default=dict)),
                (
                    "footer_height",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=6
                    ),
                ),
                ("page_numbers", models.BooleanField(default=True)),
                (
                    "page_number_position",
                    models.CharField(default="bottom_center", max_length=20),
                ),
                (
                    "page_number_format",
                    models.CharField(default="{page} of {total}", max_length=50),
                ),
                ("start_page_number", models.IntegerField(default=1)),
                ("watermark_enabled", models.BooleanField(default=False)),
                ("watermark_text", models.CharField(blank=True, max_length=255)),
                ("watermark_image", models.URLField(blank=True)),
                (
                    "watermark_opacity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.30"), max_digits=4
                    ),
                ),
                ("background_color", models.CharField(blank=True, max_length=20)),
                ("background_image", models.URLField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpreadView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("spread_type", models.CharField(default="2up", max_length=20)),
                ("pages", models.JSONField(default=list)),
                (
                    "gutter",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "spine_width",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spreads",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
