# Generated by Django 5.2.10 on 2026-01-28 12:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design_systems", "__first__"),
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        ("teams", "0003_alter_comment_mentions_alter_comment_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("wcag_criterion", models.CharField(max_length=50)),
                (
                    "wcag_level",
                    models.CharField(
                        choices=[
                            ("A", "Level A"),
                            ("AA", "Level AA"),
                            ("AAA", "Level AAA"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "wcag_principle",
                    models.CharField(
                        choices=[
                            ("perceivable", "Perceivable"),
                            ("operable", "Operable"),
                            ("understandable", "Understandable"),
                            ("robust", "Robust"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("color_contrast", "Color Contrast"),
                            ("text_size", "Text Size"),
                            ("alt_text", "Alt Text"),
                            ("focus_indicator", "Focus Indicator"),
                            ("touch_target", "Touch Target Size"),
                            ("heading_hierarchy", "Heading Hierarchy"),
                            ("link_purpose", "Link Purpose"),
                            ("form_labels", "Form Labels"),
                            ("error_identification", "Error Identification"),
                            ("language", "Language"),
                            ("consistent_navigation", "Consistent Navigation"),
                            ("timing", "Timing Adjustable"),
                            ("motion", "Motion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(default=dict)),
                ("impact", models.CharField(default="serious", max_length=20)),
                ("how_to_fix", models.TextField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Accessibility Check",
                "verbose_name_plural": "Accessibility Checks",
                "ordering": ["wcag_criterion"],
            },
        ),
        migrations.CreateModel(
            name="LintRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("spacing", "Spacing"),
                            ("alignment", "Alignment"),
                            ("color", "Color"),
                            ("typography", "Typography"),
                            ("accessibility", "Accessibility"),
                            ("naming", "Naming"),
                            ("structure", "Structure"),
                            ("components", "Components"),
                            ("assets", "Assets"),
                            ("performance", "Performance"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                            ("hint", "Hint"),
                        ],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("auto_fixable", models.BooleanField(default=False)),
                ("rule_config", models.JSONField(default=dict)),
                ("fix_config", models.JSONField(default=dict)),
                ("documentation_url", models.URLField(blank=True)),
                ("examples", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lint Rule",
                "verbose_name_plural": "Lint Rules",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "wcag_level",
                    models.CharField(
                        choices=[
                            ("A", "Level A"),
                            ("AA", "Level AA"),
                            ("AAA", "Level AAA"),
                        ],
                        default="AA",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_elements", models.IntegerField(default=0)),
                ("passed_checks", models.IntegerField(default=0)),
                ("failed_checks", models.IntegerField(default=0)),
                ("critical_issues", models.IntegerField(default=0)),
                ("serious_issues", models.IntegerField(default=0)),
                ("moderate_issues", models.IntegerField(default=0)),
                ("minor_issues", models.IntegerField(default=0)),
                ("perceivable_issues", models.IntegerField(default=0)),
                ("operable_issues", models.IntegerField(default=0)),
                ("understandable_issues", models.IntegerField(default=0)),
                ("robust_issues", models.IntegerField(default=0)),
                (
                    "compliance_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_compliant", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_reports",
                        to="projects.project",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accessibility_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Report",
                "verbose_name_plural": "Accessibility Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("serious", "Serious"),
                            ("moderate", "Moderate"),
                            ("minor", "Minor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("element_id", models.CharField(max_length=100)),
                ("element_type", models.CharField(max_length=50)),
                ("element_name", models.CharField(blank=True, max_length=255)),
                ("failure_summary", models.TextField(blank=True)),
                ("failure_data", models.JSONField(default=dict)),
                ("fix_suggestion", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("fixed", "Fixed"),
                            ("ignored", "Ignored"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accessibility_check",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="design_qa.accessibilitycheck",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="design_qa.accessibilityreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Issue",
                "verbose_name_plural": "Accessibility Issues",
                "ordering": ["impact", "element_type"],
            },
        ),
        migrations.CreateModel(
            name="DesignLintReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_issues", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                ("info_count", models.IntegerField(default=0)),
                ("auto_fixed_count", models.IntegerField(default=0)),
                ("manually_fixed_count", models.IntegerField(default=0)),
                ("ignored_count", models.IntegerField(default=0)),
                ("elements_checked", models.IntegerField(default=0)),
                ("layers_checked", models.IntegerField(default=0)),
                ("components_checked", models.IntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "health_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("improvement", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lint_reports",
                        to="projects.project",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_lint_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Lint Report",
                "verbose_name_plural": "Design Lint Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LintIgnoreRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("element", "Element"),
                            ("rule", "Rule"),
                            ("project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rule_code", models.CharField(blank=True, max_length=50)),
                ("element_id", models.CharField(blank=True, max_length=100)),
                ("reason", models.TextField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ignore_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lint_ignore_rules",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lint Ignore Rule",
                "verbose_name_plural": "Lint Ignore Rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LintIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                            ("hint", "Hint"),
                        ],
                        max_length=20,
                    ),
                ),
                ("element_id", models.CharField(max_length=100)),
                ("element_type", models.CharField(max_length=50)),
                ("element_name", models.CharField(blank=True, max_length=255)),
                ("element_path", models.CharField(blank=True, max_length=500)),
                ("position_x", models.FloatField(blank=True, null=True)),
                ("position_y", models.FloatField(blank=True, null=True)),
                ("property_name", models.CharField(blank=True, max_length=100)),
                ("current_value", models.JSONField(blank=True, null=True)),
                ("expected_value", models.JSONField(blank=True, null=True)),
                ("suggested_fix", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("fixed", "Fixed"),
                            ("ignored", "Ignored"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("auto_fixable", models.BooleanField(default=False)),
                ("fix_applied", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="design_qa.designlintreport",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_lint_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="design_qa.lintrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lint Issue",
                "verbose_name_plural": "Lint Issues",
                "ordering": ["severity", "element_type", "element_name"],
            },
        ),
        migrations.CreateModel(
            name="LintRuleSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "ruleset_type",
                    models.CharField(
                        choices=[
                            ("system", "System Default"),
                            ("custom", "Custom"),
                            ("team", "Team"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("strict_mode", models.BooleanField(default=False)),
                ("auto_fix_enabled", models.BooleanField(default=True)),
                ("error_threshold", models.IntegerField(default=0)),
                ("warning_threshold", models.IntegerField(default=10)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("icon", models.CharField(default="check-circle", max_length=50)),
                ("color", models.CharField(default="#6366f1", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lint_rule_sets",
                        to="design_systems.designsystem",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lint_rule_sets",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lint_rule_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lint Rule Set",
                "verbose_name_plural": "Lint Rule Sets",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="lintrule",
            name="rule_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="design_qa.lintruleset",
            ),
        ),
        migrations.AddField(
            model_name="designlintreport",
            name="rule_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="design_qa.lintruleset",
            ),
        ),
        migrations.AddField(
            model_name="accessibilitycheck",
            name="rule_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accessibility_checks",
                to="design_qa.lintruleset",
            ),
        ),
        migrations.CreateModel(
            name="StyleUsageReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_styles", models.IntegerField(default=0)),
                ("used_styles", models.IntegerField(default=0)),
                ("unused_styles", models.IntegerField(default=0)),
                ("unused_colors", models.JSONField(default=list)),
                ("unused_text_styles", models.JSONField(default=list)),
                ("unused_effects", models.JSONField(default=list)),
                ("unused_components", models.JSONField(default=list)),
                ("duplicate_colors", models.JSONField(default=list)),
                ("similar_colors", models.JSONField(default=list)),
                ("duplicate_text_styles", models.JSONField(default=list)),
                ("off_palette_colors", models.JSONField(default=list)),
                ("non_standard_spacing", models.JSONField(default=list)),
                ("orphaned_layers", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("potential_savings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_usage_reports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Style Usage Report",
                "verbose_name_plural": "Style Usage Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="lintrule",
            unique_together={("rule_set", "code")},
        ),
    ]
