# Generated by Django 5.2.10 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimatedExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("gif", "Animated GIF"),
                            ("mp4", "MP4 Video"),
                            ("webm", "WebM Video"),
                            ("lottie", "Lottie JSON"),
                            ("apng", "Animated PNG"),
                            ("webp", "Animated WebP"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                ("frame_start", models.IntegerField(default=0)),
                ("frame_end", models.IntegerField(blank=True, null=True)),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="animated_exports/"
                    ),
                ),
                ("output_url", models.URLField(blank=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("progress", models.FloatField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animated_exports",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animated_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GIFAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="gifs/")),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("frame_count", models.IntegerField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "static_preview",
                    models.ImageField(blank=True, null=True, upload_to="gif_previews/"),
                ),
                ("autoplay", models.BooleanField(default=True)),
                ("loop", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gif_assets",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gif_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LottieAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("json_data", models.JSONField()),
                ("file", models.FileField(blank=True, null=True, upload_to="lottie/")),
                ("version", models.CharField(blank=True, max_length=20)),
                ("frame_rate", models.FloatField(blank=True, null=True)),
                ("in_point", models.FloatField(blank=True, null=True)),
                ("out_point", models.FloatField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("autoplay", models.BooleanField(default=True)),
                ("loop", models.BooleanField(default=True)),
                ("speed", models.FloatField(default=1.0)),
                ("direction", models.IntegerField(default=1)),
                ("preview_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lottie_assets",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lottie_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Uploaded"),
                            ("youtube", "YouTube"),
                            ("vimeo", "Vimeo"),
                            ("url", "External URL"),
                            ("lottie", "Lottie Animation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="videos/")),
                ("url", models.URLField(blank=True)),
                ("embed_id", models.CharField(blank=True, max_length=100)),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("format", models.CharField(blank=True, max_length=20)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="video_thumbnails/"
                    ),
                ),
                ("autoplay", models.BooleanField(default=False)),
                ("loop", models.BooleanField(default=False)),
                ("muted", models.BooleanField(default=True)),
                ("show_controls", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_assets",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("gif", "GIF"),
                            ("lottie", "Lottie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("width", models.FloatField(default=320)),
                ("height", models.FloatField(default=180)),
                ("rotation", models.FloatField(default=0)),
                ("clip_path", models.TextField(blank=True)),
                ("border_radius", models.FloatField(default=0)),
                ("z_index", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("start_time", models.FloatField(default=0)),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("playback_rate", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gif",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media_assets.gifasset",
                    ),
                ),
                (
                    "lottie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media_assets.lottieasset",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_placements",
                        to="projects.project",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media_assets.videoasset",
                    ),
                ),
            ],
            options={
                "ordering": ["z_index"],
            },
        ),
        migrations.CreateModel(
            name="VideoFrame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("frame_number", models.IntegerField()),
                ("timestamp", models.FloatField()),
                ("image", models.ImageField(upload_to="video_frames/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="media_assets.videoasset",
                    ),
                ),
            ],
            options={
                "ordering": ["frame_number"],
                "unique_together": {("video", "frame_number")},
            },
        ),
    ]
