# Generated by Django 5.2.7 on 2025-12-03 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        ("teams", "0002_task_teamchat_teamchatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                related_name="team_mentioned_in_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_comments",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_resolved_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
