# Generated by Django 5.2.11 on 2026-02-28 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=50,
                    ),
                ),
                ("access_token", models.CharField(max_length=500)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "account_id",
                    models.CharField(
                        help_text="Platform-specific user ID", max_length=200
                    ),
                ),
                ("account_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "platform", "account_id")},
            },
        ),
        migrations.CreateModel(
            name="ScheduledPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Reference to the design project",
                        null=True,
                    ),
                ),
                ("content", models.TextField()),
                ("media_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("scheduled_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "accounts",
                    models.ManyToManyField(
                        related_name="posts", to="social_scheduler.socialaccount"
                    ),
                ),
            ],
        ),
    ]
