# Generated by Django 5.2.10 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_alter_abtest_project_alter_abtest_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("rename", "Batch Rename"),
                            ("resize", "Batch Resize"),
                            ("style", "Batch Style Change"),
                            ("transform", "Batch Transform"),
                            ("replace", "Find & Replace"),
                            ("delete", "Batch Delete"),
                            ("duplicate", "Batch Duplicate"),
                            ("align", "Batch Align"),
                            ("distribute", "Batch Distribute"),
                            ("group", "Batch Group"),
                            ("ungroup", "Batch Ungroup"),
                            ("lock", "Batch Lock"),
                            ("unlock", "Batch Unlock"),
                            ("show", "Batch Show"),
                            ("hide", "Batch Hide"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("undone", "Undone"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "component_ids",
                    models.JSONField(help_text="Array of affected component IDs"),
                ),
                ("component_count", models.IntegerField(default=0)),
                ("operation_data", models.JSONField(help_text="Operation parameters")),
                (
                    "previous_state",
                    models.JSONField(help_text="Previous state of components"),
                ),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("error_messages", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_operations",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Operation",
                "verbose_name_plural": "Batch Operations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FindReplaceOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Content"),
                            ("layer_name", "Layer Names"),
                            ("color", "Colors"),
                            ("font", "Fonts"),
                            ("effect", "Effects"),
                            ("style", "Styles"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("selection", "Selection Only"),
                            ("page", "Current Page"),
                            ("project", "Entire Project"),
                        ],
                        default="project",
                        max_length=20,
                    ),
                ),
                ("find_value", models.TextField(help_text="Value to find")),
                ("replace_value", models.TextField(help_text="Value to replace with")),
                ("use_regex", models.BooleanField(default=False)),
                ("case_sensitive", models.BooleanField(default=False)),
                ("whole_word", models.BooleanField(default=False)),
                (
                    "color_tolerance",
                    models.IntegerField(
                        default=0, help_text="Color matching tolerance (0-100)"
                    ),
                ),
                ("matches_found", models.IntegerField(default=0)),
                ("replacements_made", models.IntegerField(default=0)),
                ("affected_components", models.JSONField(default=list)),
                ("previous_state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="find_replace_ops",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="find_replace_ops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Find & Replace Operation",
                "verbose_name_plural": "Find & Replace Operations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MagicWand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "color_tolerance",
                    models.IntegerField(
                        default=10, help_text="Color matching tolerance (0-255)"
                    ),
                ),
                ("include_similar_fonts", models.BooleanField(default=False)),
                ("include_similar_sizes", models.BooleanField(default=False)),
                (
                    "size_tolerance",
                    models.FloatField(
                        default=5.0, help_text="Size tolerance in pixels"
                    ),
                ),
                (
                    "search_scope",
                    models.CharField(
                        choices=[
                            ("page", "Current Page"),
                            ("project", "Entire Project"),
                            ("selection", "Within Selection"),
                        ],
                        default="page",
                        max_length=20,
                    ),
                ),
                ("match_fill", models.BooleanField(default=True)),
                ("match_stroke", models.BooleanField(default=True)),
                ("match_font", models.BooleanField(default=False)),
                ("match_effects", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_wand_settings",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_wand_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Magic Wand Settings",
                "verbose_name_plural": "Magic Wand Settings",
            },
        ),
        migrations.CreateModel(
            name="RenameTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "pattern",
                    models.CharField(
                        help_text="Rename pattern with placeholders", max_length=500
                    ),
                ),
                ("start_number", models.IntegerField(default=1)),
                ("number_step", models.IntegerField(default=1)),
                ("preserve_extension", models.BooleanField(default=True)),
                (
                    "case_transform",
                    models.CharField(
                        choices=[
                            ("none", "No Change"),
                            ("lower", "lowercase"),
                            ("upper", "UPPERCASE"),
                            ("title", "Title Case"),
                            ("sentence", "Sentence case"),
                            ("camel", "camelCase"),
                            ("pascal", "PascalCase"),
                            ("snake", "snake_case"),
                            ("kebab", "kebab-case"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rename_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rename Template",
                "verbose_name_plural": "Rename Templates",
                "ordering": ["-is_favorite", "-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResizePreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "resize_mode",
                    models.CharField(
                        choices=[
                            ("absolute", "Absolute Size"),
                            ("scale", "Scale Factor"),
                            ("fit", "Fit to Size"),
                            ("fill", "Fill to Size"),
                            ("width", "Set Width (Proportional)"),
                            ("height", "Set Height (Proportional)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("scale_x", models.FloatField(default=1.0)),
                ("scale_y", models.FloatField(default=1.0)),
                ("maintain_aspect_ratio", models.BooleanField(default=True)),
                (
                    "anchor",
                    models.CharField(
                        choices=[
                            ("top-left", "Top Left"),
                            ("top-center", "Top Center"),
                            ("top-right", "Top Right"),
                            ("center-left", "Center Left"),
                            ("center", "Center"),
                            ("center-right", "Center Right"),
                            ("bottom-left", "Bottom Left"),
                            ("bottom-center", "Bottom Center"),
                            ("bottom-right", "Bottom Right"),
                        ],
                        default="center",
                        max_length=20,
                    ),
                ),
                ("round_to_pixels", models.BooleanField(default=True)),
                ("min_width", models.FloatField(blank=True, null=True)),
                ("min_height", models.FloatField(blank=True, null=True)),
                ("max_width", models.FloatField(blank=True, null=True)),
                ("max_height", models.FloatField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resize_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resize Preset",
                "verbose_name_plural": "Resize Presets",
                "ordering": ["-is_favorite", "-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="SelectionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "selection_query",
                    models.JSONField(help_text="Query that was used or inferred"),
                ),
                (
                    "selected_ids",
                    models.JSONField(help_text="IDs of selected components"),
                ),
                ("component_count", models.IntegerField(default=0)),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="Action taken after selection",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selection_history",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selection_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Selection History",
                "verbose_name_plural": "Selection History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartSelectionPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "preset_type",
                    models.CharField(
                        choices=[
                            ("layer_type", "By Layer Type"),
                            ("property", "By Property"),
                            ("style", "By Style"),
                            ("name", "By Name Pattern"),
                            ("size", "By Size"),
                            ("position", "By Position"),
                            ("custom", "Custom Query"),
                        ],
                        max_length=20,
                    ),
                ),
                ("query", models.JSONField(help_text="Selection query in JSON format")),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("keyboard_shortcut", models.CharField(blank=True, max_length=50)),
                ("use_count", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System presets cannot be deleted"
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selection_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Selection Preset",
                "verbose_name_plural": "Smart Selection Presets",
                "ordering": ["-is_favorite", "-use_count", "name"],
            },
        ),
    ]
