# Generated by Django 5.2.10 on 2026-01-29 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_batchoperation_project_and_more"),
        ("smart_tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchoperation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_operations_smart_tools",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="batchoperation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_operations_smart_tools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
