# Generated by Django 5.2.11 on 2026-02-28 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design_systems", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandKitEnforcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lock_color_picker",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent team from using off-brand hex codes",
                    ),
                ),
                (
                    "force_ai_variants",
                    models.BooleanField(
                        default=False,
                        help_text="Force AI to strictly adhere to brand colors over general generation",
                    ),
                ),
                (
                    "lock_typography",
                    models.BooleanField(
                        default=False,
                        help_text="Pre-define Heading/Body fonts and disable custom selections",
                    ),
                ),
                (
                    "require_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Require Admin approval before exporting/publishing if edits were made by a Junior role",
                    ),
                ),
                (
                    "log_violations",
                    models.BooleanField(
                        default=True,
                        help_text="Keep a log of when users try to break brand rules",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_enforcement",
                        to="design_systems.designsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrandViolationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g., 'invalid_hex', 'unapproved_font'",
                        max_length=100,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, help_text="Context of violation", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "enforcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="brand_kit.brandkitenforcement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brand_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
